### ISSUE TITLE
Can't compile `tests/expectations` on macOS version 10.12.6

### ISSUE THREAD

**Issue by alexeyzab** [rust-lang-nursery/rust-bindgen#1004]
After running

```
cd tests/expectations
cargo test
```

I get the following error:
```
error: no rules expected the token `,`
  --> tests/objc_class_method.rs:61:60
   |
61 |             methodWithArg1: intvalue: ::std::os::raw::c_int,
   |                                                            ^

error: aborting due to previous error

error: Could not compile `tests_expectations`.
```

**Comment by fitzgen** [comment]
It looks like this is trying to define two properties or something: `<prop1>: <prop2>: <type>,` or something like that. Probably fall out from the move off of `syntex` to `quote`.

Check out the `objc` related things in `src/codegen/mod.rs`.

Should be a fairly easy fix for someone with with a mac.

**Comment by alexeyzab** [comment]
@highfive: assign me

**Comment by alexeyzab** [comment]
The expectations tests compile after I manually do the following edits:

Add `!#[feature(type_ascription)]` to `objc_class_method.rs`,  `objc_method.rs`, `objc_property_fnptr.rs`.
Remove several commas from [objc_method.rs](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/tests/expectations/tests/objc_method.rs#L48-L49), [objc_class_method](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/tests/expectations/tests/objc_class_method.rs#L61-L62).

As you've mentioned, the commas are added because of something in `src/codegen/mod.rs`, how about the `!#[feature(type_ascription)]` part? I am a little bit lost here.

**Comment by fitzgen** [comment]
Ok, I didn't realize that this was inside the `objc` crate's `msg_send!` macro, so ignore everything I said.

It looks like `msg_send!` doesn't expect any commas between arguments: http://sasheldon.com/rust-objc/objc/macro.msg_send.html

Yet, inside the `objc::format_method_call` function in `src/codegen/mod.rs`, we are joining each argument with a comma:

```rust
        quote! {
            #( #args ),*
        }
```

The `#(...),*` means join with comma, `#(...);*` would be join with semicolon, `#(...)*` would be join with no separator.

I *think* we can just remove that `,` and join without any separator and then the tests should pass.
