### ISSUE TITLE
dump_preprocessed_input test fails on Windows when checked out with CRLF line endings

### ISSUE THREAD

**Issue by AndrewGaspar** [rust-lang-nursery/rust-bindgen#1023]
On Windows, typically users set the git `core.autocrlf=true` option to checkout files with Windows-style line endings, but to checkin with Unix-style line endings.

The dump_preprocessed_input test validates that an output file `__bindgen.ii` contains an input file `arg_keyword.hpp`. However, `__bindgen.ii` is output with LF line endings, and so arg_keyword.hpp's contents do not match.

I've validated the test passes if you check out the repo with LF line endings.

**Comment by AndrewGaspar** [comment]
The reason this doesn't seem to be an issue with the rest of the tests is because rustfmt normalizes the line endings to LF when doing the comparison

**Comment by AndrewGaspar** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
FYI @AndrewGaspar, if you add `Fixes #12345` to the commit message or PR comment, then github will automatically close the issue when the PR is merged :)
