### ISSUE TITLE
`root` module name and visibility

### ISSUE THREAD

**Issue by grovesNL** [rust-lang-nursery/rust-bindgen#1027]
I'm wondering if there is interest in being able to provide a custom name instead of `root`, or marking this module as `pub(crate)`. Based on the [code generation](https://github.com/rust-lang-nursery/rust-bindgen/blob/fcbe260eacd10df38b563d9658203293d4e1f8ec/src/codegen/mod.rs#L421) it doesn't seem possible to change the name or visibility at the moment.

One use case would be libraries that don't want to expose the generated bindings, or prefer to export them under a different name. If there is another way to accomplish this already, please let me know.

**Comment by grovesNL** [comment]
Thinking about this some more, we can already do this in place wherever we use `include!`. So I don't think this customization is necessary.

**Comment by fitzgen** [comment]
Yeah, the other trick is to add `pub use root::*` as a raw line, or above the `include!` if that is what you're looking for.
