### ISSUE TITLE
Our C-Smith driver should ask bindgen to derive everything

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#1037]
Might as well cover all the bases...

See `csmith-fuzzing/driver.py`. The `run_bindgen` function should pass all the derive-enabling command line flags listed via `bindgen --help`.

**Comment by clippered** [comment]
looks pretty straightforward as my first work :)
@highfive: assign me

**Comment by fitzgen** [comment]
Let me know if you run into any questions @clippered :)

**Comment by clippered** [comment]
@fitzgen Should this be closed now that https://github.com/rust-lang-nursery/rust-bindgen/pull/1043 has been merged? Thanks

**Comment by fitzgen** [comment]
Yes, thanks! In the future, if you add `Fixes #12345` to commit messages, then github will auto close them :)

**Comment by clippered** [comment]
Will do it next time, cheers.
