### ISSUE TITLE
The link options are ignored.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#104]
It seems that I dropped them during the rewrite, can't remember if I did it accidentally or not.

In any case, we announce to support it and don't, which should be fixed either removing the option or supporting it properly.

**Comment by jdub** [comment]
What should they do? Detect if its running in `build.rs` and print `cargo:rustc-link-lib=` lines? Add `#[link]` attributes?

**Comment by emilio** [comment]
The old behavior for this option is to create `#[link]` attributes. I'm still pretty dubious it's the right functionality to have builtin support for in bindgen, but some people seemed to disagree on IRC and found it useful.

**Comment by metajack** [comment]
This is probably a good thing to ask @alexcrichton

**Comment by alexcrichton** [comment]
`rustc-link-lib` and `#[link]` are equivalent, so it shouldn't matter which is used

**Comment by metajack** [comment]
I think in the past we've preferred rustc-link-lib because having this information outside of build.rs made a mess.

**Comment by jdub** [comment]
OK, for now I'll spit out `rustc-link-lib` directives if we're in `build.rs`, and otherwise continue to ignore the link flags.

I'll fix this with my docopt changes in servo/rust-bindgen#202.

**Comment by jdub** [comment]
Hmm, I might hold off and do it separately. It's unclear when it should happen in the library use case: On `generate()` or `write()`? Probably `write()`, but your feedback would be appreciated.

**Comment by jsgf** [comment]
I was expecting these options to add `#[link]` to the extern block. I'm currently faking this with `--raw-line=#[link(name = "mylib++")] extern {}` which seems OK, but I'm concerned that a future version of the compiler would treat the `extern {}` as useless and drop it - I'd feel more comfortable if it were attached to an extern block with signatures in it.

build.rs-based approaches aren't useful for me because I'm not using cargo to build.

**Comment by ryankurte** [comment]
Updating stuff from a previous bindgen / rust version, and also not using cargo to build. Is there a recommended solution for this?
Current approach is `sed -i '' 's/^extern "C" {/#[link(name = "${LIBNAME}")] extern "C" {/' ${FILENAME}`.

**Comment by emilio** [comment]
@ryankurte I believe the cleanest solution for this is `--raw-line` for now. I don't have the time right now to implement this, but I'm happy to mentor anyone wanting to do so.

**Comment by ryankurte** [comment]
Oh right! Trouble there is that raw line only seems to accept one line, and
I have also had to blacklist and manually replace some types. Might be
cleaner for now just to cat two files together.
Cheers for the response, I will have a nosey into it if I have some time.

**Comment by mitchmindtree** [comment]
FWIW I'm getting the same issue even when generating the bindings using a `build.rs` script - [see the build script on the branch here](https://github.com/mitchmindtree/coreaudio-sys/blob/bindgen/build.rs). Perhaps i'm incorrectly linking the frameworks here?

**Comment by mitchmindtree** [comment]
Ah, disabling `trust_clang_mangling` seems to fix linking with the build.rs-generated approach.
