### ISSUE TITLE
Unsigned global set to -1

### ISSUE THREAD

**Issue by e00E** [rust-lang-nursery/rust-bindgen#1040]
### Input C/C++ Header

```C++
unsigned long long g_107 = 18446744073709551615UL;
```

### Bindgen Invocation

```
bindgen failing.h -o failing.rs
```

### Actual Results

Bindgen generates
```rust
pub const g_107: ::std::os::raw::c_ulonglong = -1;
```
which when compiled with `rustc --crate-type lib --test -o out failing2.rs` gives
```
error[E0600]: cannot apply unary operator `-` to type `u64`
 --> failing2.rs:3:48
  |
3 | pub const g_107: ::std::os::raw::c_ulonglong = -1;
  |                                                ^^

error: aborting due to previous error
```

### Expected Results
Not sure, but `18446744073709551615` does not look like `-1` in the first place.
Found with csmith fuzzing.

**Comment by pepyakin** [comment]
> Not sure, but 18446744073709551615 does not look like -1 in the first place.
Found with csmith fuzzing.

In fact it is!
`hex(18446744073709551615)` = `0xFFFF_FFFF_FFFF_FFFF` which is `-1` in signed interpretation. See [Two's complement](https://en.wikipedia.org/wiki/Two%27s_complement).

This happens because bindgen doesn't check for a signedness of type, it just emits as [signed var](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/codegen/mod.rs#L477) with [int_expr](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/src/codegen/helpers.rs#L129-L134).

**Comment by fitzgen** [comment]
Thanks for the bug report @e00E ! Did you use C-Smith and C-Reduce?

This should be easy enough to fix by making signed and unsigned versions of the codegen helpers that @pepyakin linked to.

**Comment by e00E** [comment]
I did use csmith but not C-reduce. I manually cut out everything except the part responsible for the error.

**Comment by josh0588** [comment]
Hi I'd like to start contributing and take this on as my first bug!
@highfive: assign me

**Comment by fitzgen** [comment]
@josh0588 if you run into any questions, don't hesitate to ask :)

**Comment by josh0588** [comment]
@fitzgen thanks, it appears there already is a signed and unsigned version of the codegen helpers 'uint_ expr'? but the match construct only calls the int_expr

**Comment by fitzgen** [comment]
@josh0588 ah, I forgot about that! Looks like we jsut need to call it at the right time then :)

**Comment by fitzgen** [comment]
Hi @josh0588 -- still making progress here? Any questions I can answer for you?

**Comment by fitzgen** [comment]
I'm taking this due to inactivity and because it is being hit by `csmith` all the time, preventing us from digging too much deeper.

@josh0588, if you're interested in hacking on another issue, let me know and I can help you find something :)
