### ISSUE TITLE
Wrong layout for union with bitfields

### ISSUE THREAD

**Issue by pepyakin** [rust-lang-nursery/rust-bindgen#1056]
See original issue https://github.com/rust-lang-nursery/rust-bindgen/issues/1034

### Input C/C++ Header

Generated by C-Smith and reduced by `creduce`:

```c
union U4 {
  unsigned : 1
};
```

### Bindgen Invocation

```
$ bindgen input.h --with-derive-partialeq --with-derive-eq
```

### Actual Results

```
running 1 test
test bindgen_test_layout_U4 ... FAILED

failures:

---- bindgen_test_layout_U4 stdout ----
	thread 'bindgen_test_layout_U4' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`: Size of: U4', /var/folders/cd/c9707gm91qj22fkb99clygfm0000gn/T/bindings.rs.XXXXXX.E24MhMan:58:4

failures:
    bindgen_test_layout_U4

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### Expected Results

No layout test failures.

**Comment by pepyakin** [comment]
Seems like we have a different problem in the size case.

Let's consider this header:

```
union U4 {
  unsigned : 1
};
```

in generated bindings assert test is failing

```rust
assert_eq!(
    ::std::mem::size_of::<U4>(),
    1usize,
    concat!("Size of: ", stringify!(U4))
);
```

and it makes sense if we look at `U4` definition:

```rust
#[repr(C)]
#[derive(Copy)]
pub struct U4 {
    pub _bitfield_1: u8,
    pub bindgen_union_field: u8,
}
```

there are 2 disjoint fields, and this is clearly wrong. 

I suppose in this case we shouldn't generate `_bitfield_1` but should refer `bindgen_union_field` in bitfield's accessors.

**Comment by emilio** [comment]
This is a dupe of #744, I believe.

**Comment by pepyakin** [comment]
Agree, closing.
