### ISSUE TITLE
Tests started to fail on macOS on the most recent master

### ISSUE THREAD

**Issue by pepyakin** [rust-lang-nursery/rust-bindgen#1067]
https://github.com/rust-lang-nursery/rust-bindgen/commit/745d60610ec6979368fc240472f7c04a3e04f282 made tests on my local macOS machine to fail.

```shell
$ sw_vers

ProductName:    Mac OS X
ProductVersion:    10.12.6
BuildVersion:    16G29
```

```shell
$ clang --version

Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Here is [build log](https://gist.github.com/pepyakin/7627b1dc2fd89445baad92bff8ce1b6d).

**Comment by emilio** [comment]
Hmm, right. Now we have the problem that symbols on those platforms are actually different. :(

**Comment by emilio** [comment]
So, options I'm seeing:

 * Run tests with a linux64 target by default. That's easiest, but likely misses support? Also, `test_expectations` probably won't build.

 * Reverting that for now, or hiding it behind an option. We really want proper unmangled symbols instead of tracking down all the platforms it affects.

 * Add tests per-platform, and run them with different `--target` values.

 * Make the runner ignore trivial `link_name` differences?

**Comment by liranringel** [comment]
@emilio As I understand it, the functionality is correct, but the tests need refactor.
That fix is something I've been waiting for some time (for the `ipconfig` and `trust-dns` crates), and it's unfortunate if it won't land on version 0.31.

**Comment by emilio** [comment]
Right, I agree, and I think reverting would be really unfortunate. We probably just need an easy way to update tests for all platforms (can be done with `--target`) and build tests for the correct platform.

**Comment by fitzgen** [comment]
> Run tests with a linux64 target by default. That's easiest, but likely misses support? Also, test_expectations probably won't build.

Inserting an implicit `--target` if there isn't one explicitly specified is probably easiest.

Note that the test expectations don't actually call any of the declared functions, so we won't get link errors (otherwise, we would get them now).
