### ISSUE TITLE
csmith: Wrong size of struct with bitfields

### ISSUE THREAD

**Issue by pepyakin** [rust-lang-nursery/rust-bindgen#1076]
### Input C/C++ Header

```C++
struct S1 {
  signed : 15;
  unsigned : 6
};
```

### Bindgen Invocation

Predicate invocation:
```
predicate.py \
    --bindings-grep "S1" \
    --expect-layout-tests-fail \
    --layout-tests-grep "Size of\: S1" \
    ./header.h
```

([bindgen args](https://github.com/rust-lang-nursery/rust-bindgen/blob/83156461266e80c426dcd4aee135a17b1dab3f18/csmith-fuzzing/predicate.py#L35))

### Actual Results

Layout test panic:
```
thread 'bindgen_test_layout_S1' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`: Size of: S1', /var/folders/cd/c9707gm91qj22fkb99clygfm0000gn/T/bindings-q9aa57t5.rs:3:207
```

Generated bindings:

```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Default, Copy, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct S1 {
    pub _bitfield_1: [u16; 2usize],
    pub __bindgen_align: [u8; 0usize],
}
#[test]
fn bindgen_test_layout_S1() {
    assert_eq!(
        ::std::mem::size_of::<S1>(),
        3usize,
        concat!("Size of: ", stringify!(S1))
    );
    assert_eq!(
        ::std::mem::align_of::<S1>(),
        1usize,
        concat!("Alignment of ", stringify!(S1))
    );
}
impl Clone for S1 {
    fn clone(&self) -> Self {
        *self
    }
}
impl S1 {
    #[inline]
    pub fn new_bitfield_1() -> u32 {
        0
    }
}
```

### Expected Results

No layout test failures.

**Comment by fitzgen** [comment]
Looks like our bitfield unit allocation is off. This probably should be two units: one `u16` and one `u8`. And then they should be packed to alignment of `1` (which I don't understand why from the definition...).

**Comment by pepyakin** [comment]
This is somehow related to the fact that the bitfields are unnamed.

Consider [this snippet](https://godbolt.org/g/w3bftL). It will return 3 for size and 1 for alignment. But if you give a name to either field, both size and align will return 4.

**Comment by fitzgen** [comment]
I guess anonymous bitfields only contribute to size, not alignment? Intuitively, that makes sense because they can never be read, so unaligned reads are a non-issue.

At this point, I think we really need to go through the ABI's text and carefully translate the algorithms described therein...
