### ISSUE TITLE
Help: bindgen not getting everything from libzip

### ISSUE THREAD

**Issue by danielpclark** [rust-lang-nursery/rust-bindgen#1088]
Hey all, this is my first time trying to do this so I went with what I thought might be an easier project to port over to Rust.  I'm using bindgen with [libzip](https://github.com/nih-at/libzip) and I've followed the default example in the guide and everything seems to pass.  But looking at the results of `cargo test` it looks like I'm not getting what I want to get.

The repo is here: https://github.com/danielpclark/zip-sys and it's pretty much the same as the documentation example.  I've installed libzip on my system and I've used `#include <zip.h>` in my wrapper.h file but the test results are this:

```
running 32 tests
test bindgen_test_layout__G_fpos_t ... ok
test bindgen_test_layout__G_fpos64_t ... ok
test bindgen_test_layout__IO_marker ... ok
test bindgen_test_layout___locale_struct ... ok
test bindgen_test_layout___fsid_t ... ok
test bindgen_test_layout__IO_FILE ... ok
test bindgen_test_layout___mbstate_t ... ok
test bindgen_test_layout___mbstate_t__bindgen_ty_1 ... ok
test bindgen_test_layout___va_list_tag ... ok
test bindgen_test_layout___sigset_t ... ok
test bindgen_test_layout___pthread_internal_list ... ok
test bindgen_test_layout_fd_set ... ok
test bindgen_test_layout_imaxdiv_t ... ok
test bindgen_test_layout_itimerspec ... ok
test bindgen_test_layout_pthread_attr_t ... ok
test bindgen_test_layout_pthread_barrier_t ... ok
test bindgen_test_layout_pthread_barrierattr_t ... ok
test bindgen_test_layout_pthread_cond_t ... ok
test bindgen_test_layout_pthread_cond_t__bindgen_ty_1 ... ok
test bindgen_test_layout_pthread_condattr_t ... ok
test bindgen_test_layout_pthread_mutex_t ... ok
test bindgen_test_layout_pthread_mutex_t___pthread_mutex_s ... ok
test bindgen_test_layout_pthread_mutexattr_t ... ok
test bindgen_test_layout_pthread_rwlock_t ... ok
test bindgen_test_layout_pthread_rwlock_t__bindgen_ty_1 ... ok
test bindgen_test_layout_timespec ... ok
test bindgen_test_layout_tm ... ok
test bindgen_test_layout_pthread_rwlockattr_t ... ok
test bindgen_test_layout_zip_source_args_seek ... ok
test bindgen_test_layout_timeval ... ok
test bindgen_test_layout_zip_stat ... ok
test bindgen_test_layout_zip_error ... ok

test result: ok. 32 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

This list does not appear to contain the structs or methods I'm looking for.  This is the header the wrapper includes https://github.com/nih-at/libzip/blob/master/lib/zip.h and I believe it indirectly includes https://github.com/nih-at/libzip/blob/master/lib/zipint.h which has the structs and methods I'm more interested in.  But the installation of libzip does not include a `zipint.h` file for me to use from the same place `zip.h` is put.  Can you tell me what I need to do here?

**Comment by RReverser** [comment]
@danielpclark It looks like it's the other way around - `zipint.h` includes `zip.h` here, so you need to pass `zipint.h` to bindgen instead.

**Comment by danielpclark** [comment]
> It looks like it's the other way around - zipint.h includes zip.h here, so you need to pass zipint.h to bindgen instead.

I've tried that.  But the installation of libzip does not include zipint.h within the systems include path.

```
cargo test
   Compiling zip-sys v0.0.2 (file:///home/danielpclark/dev/zip-sys)
error: failed to run custom build command for `zip-sys v0.0.2 (file:///home/danielpclark/dev/zip-sys)`
process didn't exit successfully: `/home/danielpclark/dev/zip-sys/target/debug/build/zip-sys-ec1b982374fb125a/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=zip
wrapper.h:1:10: fatal error: 'zipint.h' file not found, err: true

--- stderr
wrapper.h:1:10: fatal error: 'zipint.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ()', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
---

```bash
# whereis zip.h
zip: /usr/bin/zip /usr/include/zip.h /usr/share/man/man1/zip.1.gz
# whereis zipint.h
zipint:
```

Would manually copying the contents of `zipint.h` into `wrapper.h` possibly work?

**Comment by RReverser** [comment]
> But the installation of libzip does not include zipint.h within the systems include path.

You might want to check this thread https://nih.at/listarchive/libzip-discuss/msg00087.html

Sounds like `zipint.h` is internal header, but yeah, assuming you get a compatible version, you can copy it into your sources directory or even add libzip as a submodule etc.

**Comment by danielpclark** [comment]
Thank you.
