### ISSUE TITLE
Constructors with initializer list.

### ISSUE THREAD

**Issue by not-fl3** [rust-lang-nursery/rust-bindgen#1117]
### Input C/C++ Header

```C++
class A {
  int Y;

  A() : Y(5) {  }
};
```
### Bindgen Invocation

```$ bindgen test.hpp```

### Actual Results

Just a normal struct without any impls.
```
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub Y: ::std::os::raw::c_int,
}
```

### Expected Results

Default implementation or new method with initializer list data.

**Comment by emilio** [comment]
Inline constructors are not quite supported, because there's nothing rust can call to. See https://rust-lang-nursery.github.io/rust-bindgen/faq.html#why-isnt-bindgen-generating-bindings-to-inline-functions.

Thanks for the report!
