### ISSUE TITLE
Global multi-level pointers

### ISSUE THREAD

**Issue by snewt** [rust-lang-nursery/rust-bindgen#1151]
Hello, 
I've been working toward implementing property based testing with quickcheck, issue #970 and the tests I have so far are generating some code that fails. 

### Input C/C++ Header
```C++
int ***** simple_decl_71; // fail, 5 levels
// int **** simple_decl_71; // succeed, 4 levels
// int ***** simp_decl_71; // succeed, 5 levels with variable name less than 13 characters
```
It seems like this is only an issue for globals as far as I can tell because the following code succeeds
```C++
struct struct_43 {
    int ***** simple_decl_71; // succeed, 5 levels with variable name greater than 12 characters
};
```

### Invocation

I've been using the `csmith-fuzzing/predicate.py` script to test so the failing invocation would look like this assuming that line is in a header named multi-level.h

```
$ ./csmith-fuzzing/predicate.py multi-level.h
```

### Actual Results

```
Running: ['cargo', 'run', '--manifest-path', '/home/username/src/rust-bindgen/Cargo.toml', '--', 'multi-line.h', '-o', '/tmp/bindings-fzw0x4sl.rs', '--with-derive-partialeq', '--with-derive-eq', '--with-derive-partialord', '--with-derive-ord', '--with-derive-hash', '--with-derive-default']
Running: ['rustc', '--crate-type', 'lib', '--test', '-o', '/tmp/layout-tests-65v9sdg9', '/tmp/bindings-fzw0x4sl.rs']
Error: running `rustc` on the emitted bindings failed
+error: expected item after attributes
+ --> /tmp/bindings-fzw0x4sl.rs:4:44
+  |
+4 |  # [ link_name = "\u{1}_Z14simple_decl_71" ]
+  |                                            ^
+
+error: aborting due to previous error
+
```
Generated code:
```rust
extern "C" {
 # [ link_name = "\u{1}_Z14simple_decl_71" ]
    ;
}
```
### Expected Results

Generated code that looks like this:
```rust
extern "C" {
 # [ link_name = "\u{1}_Z14simple_decl_71" ]
    pub static mut simple_decl_71: *mut *mut *mut *mut *mut ::std::os::raw::c_int;
}
```

**Comment by fitzgen** [comment]
Thanks for filing a bug @snewt !

I can't reproduce the behavior you're describing however. I wonder if it is possibly due to an older version of `rustfmt`? Do you experience the same issue with either

* adding `--no-rustfmt-bindings` to the args passed to `bindgen` through `predicate.py`, or
* after ensureing that `rustfmt` is up-to-date? 

```
$ rustup update nightly
$ cargo +nightly install -f rustfmt-nightly
```

Thanks!

**Comment by snewt** [comment]
Ah! @fitzgen the update steps you provided resolved the issue, thanks for walking me through them.

**Comment by fitzgen** [comment]
Great!
