### ISSUE TITLE
Can not load local header 

### ISSUE THREAD

**Issue by VikingMew** [rust-lang-nursery/rust-bindgen#1155]
### Input C/C++ Header

https://github.com/dmlc/dmlc-core/blob/43568062af426ee1e970e480e770b13f5a60f2e8/include/dmlc/base.h#L189

### Bindgen Invocation

```Rust
    let bindings = bindgen::Builder::default()
        .header("include/wrapper.h")
        .enable_cxx_namespaces()
        .clang_arg("-I/../include")
        .generate()
        .expect("Unable to generate bindings");
```

### Actual Results
cargo:rustc-link-search=mxnet
cargo:rustc-link-lib=bz2
cargo:rustc-link-lib=mxnet
include/mxnet/./base.h:27:10: error: 'dmlc/base.h' file not found with <angled> include; use "quotes" instead, err: true
include/mxnet/dmlc/./base.h:189:8: error: expected identifier or '(', err: true
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:50:1: error: unknown type name 'namespace', err: true
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:50:43: error: expected ';' after top level declarator, err: true

**Comment by fitzgen** [comment]
> .clang_arg("-I/../include")

Is that leading `/` supposed to be there? I'd expect `.clang_arg("-I../include")` or some such instead.

This whole issue looks like

1. include dir misconfiguration, and
2. maybe some syntax errors in whatever headers are getting included (although maybe they will go away after fixing the first issue).

**Comment by VikingMew** [comment]
I just tested your args. `.clang_arg("-I../include")`
It solves the first line `; use "quotes" instead,`
but not the latter few lines. 
```
cargo:rustc-link-lib=mxnet
include/mxnet/dmlc/./base.h:189:8: error: expected identifier or '(', err: true
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:50:1: error: unknown type name 'namespace', err: true
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:50:43: error: expected ';' after top level declarator, err: true
/usr/include/wchar.h:147:8: error: unknown type name 'wchar_t', err: true
```
still exists.

**Comment by fitzgen** [comment]
Those are all syntax errors from `libclang` -- can you compile a simple `.cpp` file that includes those same headers with the same flags passed to `.clang_arg` + `-c`?

**Comment by fitzgen** [comment]
Do you have `.clang_arg("-x").clang_arg("c++")`? Or try renaming you `wrapper.h` to `wrapper.hpp`

**Comment by VikingMew** [comment]
`.clang_arg("-x").clang_arg("c++")` works. Thank you.
