### ISSUE TITLE
Regression from 0.30.0 to 0.31

### ISSUE THREAD

**Issue by siscia** [rust-lang-nursery/rust-bindgen#1156]
Sorry guys, honestly I am not even sure it is a bindgen issue.

I have this project that compiles just fine with bindgen previous or equal to 0.30.0 but it is broken on bindgen 0.31.3

Now, if I run just bindgen it outputs a reasonable file, however, the file does not compile.

### Input C/C++ Header
This is quite an issue, I wasn't able to follow the instruction to generate the minimun test case, sorry about that.

Anyway, in the repo you can check that everything compiles given bindgen <= 0.30.0, if you change it to 0.31.x it will break.

### Bindgen Invocation

```Rust
    let bindings = bindgen::Builder::default()
        .parse_callbacks(Box::new(SqliteTypeChooser))
        .header("sqlite_dependencies.h")
        .generate()
        .expect("Unable to generate bindings for SQLite");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings.write_to_file(out_path.join("bindings_sqlite.rs"))
        .expect("Couldn't write bindings for SQLite!");
```

### Actual Results

```
  │error[E0277]: the trait bound `[u8; 48]: std::clone::Clone` is not satisfied
  │   --> /home/simo/rediSQL/target/debug/build/rediSQL-fe3bbd615f1d0539/out/bindings_sqlite.rs:466:80
  │    |
  │466 | } # [ repr ( C ) ] # [ derive ( Copy , Clone ) ] pub struct sqlite3_snapshot { pub hidden : [ :: std :: os :: raw :: c_uchar ; 48usize ] , } 
  │# [ test ] fn bindgen_test_layout_sqlite3_snapshot ( ) { assert_eq ! ( :: std :: mem :: size_of :: < sqlite3_snapshot > ( ) , 48usize , concat ! ( 
  │"Size of: " , stringify ! ( sqlite3_snapshot ) ) ) ; assert_eq ! ( :: std :: mem :: align_of :: < sqlite3_snapshot > ( ) , 1usize , concat ! ( "Ali
  │gnment of " , stringify ! ( sqlite3_snapshot ) ) ) ; assert_eq ! ( unsafe { & ( * ( 0 as * const sqlite3_snapshot ) ) . hidden as * const _ as usiz
  │e } , 0usize , concat ! ( "Alignment of field: " , stringify ! ( sqlite3_snapshot ) , "::" , stringify ! ( hidden ) ) ) ; } extern "C" {
  │    |                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the 
  │trait `std::clone::Clone` is not implemented for `[u8; 48]`
  │    |
  │    = help: the following implementations were found:
  │              <[T; 24] as std::clone::Clone>
  │              <[T; 6] as std::clone::Clone>
  │              <[T; 16] as std::clone::Clone>
  │              <[T; 0] as std::clone::Clone>
  │            and 29 others
  │    = note: required by `std::clone::AssertParamIsClone`
  │
  │error: aborting due to previous error

```

### Expected Results

It should compile.

### Reference

The commit where I update bindgen is this one: https://github.com/RedBeardLab/rediSQL/commit/197f898b4dbb079f92f426865b00be2ffe29d7b3

To reproduce the fastest thing is just to clone the repo and run `cargo build`

Sorry that I wasn't able to provide more info...

**Comment by klefevre** [comment]
We had the same problem it could be related to #1120 .

The solution is to install the nightly version of rustfmt:
`rustup update; rustup run nightly cargo install rustfmt-nightly` on your system.

**Comment by fitzgen** [comment]
Yes, this is a bug in `rustfmt`. You can update it to get the fix, as @klefevre kindly pointed out, or you can use `.rustfmt_bindings(false)`.

Thanks for the bug report!
