### ISSUE TITLE
enum: "bitfield" and "rustified" shouldn't be mutually exclusive

### ISSUE THREAD

**Issue by tamird** [rust-lang-nursery/rust-bindgen#1165]
Providing the two together should provide an API similar to that produced by usage of the [bitflags crate](https://github.com/rust-lang-nursery/bitflags).

**Comment by nox** [comment]
That's not an obvious thing to do without `#[repr(transparent)]`. For any given `T` type with `#[repr(C)]`, `T` and `#[repr(C)] struct Wrapper(T)` won't necessarily behave the same on some ABIs.

**Comment by nox** [comment]
Though I just remembered that's already a problem with "bitfield" on its own, IIRC.

**Comment by emilio** [comment]
Yeah, but more to the point, bitfield + rustified is a no-go because of rust `match` semantics, see #225. Having out-of-range rust enums is UB.

**Comment by tamird** [comment]
Ah, sorry, I should have titled this differently - I don't need the enum part, I just need it to be associated constant-y. Should I open a new issue for non-rustified associated constant enums?

**Comment by emilio** [comment]
Wait, you mean generating them in their own modules? Ok, yeah, that should be doable :)

But yeah, let's file another issue for them, since this one has nothing related to it.
