### ISSUE TITLE
enum: support bitfield enums that use associated constants

### ISSUE THREAD

**Issue by tamird** [rust-lang-nursery/rust-bindgen#1166]
I think a composition between `rustified_enum` and `constified_enum_module` would achieve this, but I believe they're mutually exclusive today.

**Comment by tamird** [comment]
Actually that composition won't quite do it, since I really want associated constants on the type rather than a module that contains the type and all the variants.

**Comment by emilio** [comment]
Fixed by #1293, please reopen if not the case.
