### ISSUE TITLE
Builder::command_line_flags misgenerates rust target's flag

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#1182]
It should add `["--rust-target", "1.19"]` but only adds the second part.

See the `command_line_flags` method of `Builder` in `src/lib.rs`.

There are some tests that can be extended at the bottom of the file.

**Comment by manaskarekar** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
Thanks!
