### ISSUE TITLE
Rustfmt is not run if rustup exists, but nightly toonchain/rustfmt-nightly is not installed

### ISSUE THREAD

**Issue by Kobata** [rust-lang-nursery/rust-bindgen#1184]
[This code](https://github.com/rust-lang-nursery/rust-bindgen/blob/433e9c050b2f5fd45a476a818f035b17b38f6b15/src/lib.rs#L1715) will attempt to run `rustup run nightly rustfmt` in *any* situation that `rustup` is available, without fallback to the non-nightly version in the event it fails, for instance due to there not being an installed nightly toolchain.

It appears to have been introduced by #1042

Obviously, there are some known issues with 'old' versions of `rustfmt`, so prioritizing nightly when possible isn't that bad an idea, however currently there is no fallback of any sort short of preventing bindgen from finding any `rustup` binary.

**Comment by manaskarekar** [comment]
IIRC, non-nightly rustfmt would fail, so we chose to use rustfmt nightly, or none at all. 

Please correct me if I'm remembering incorrectly.

**Comment by Kobata** [comment]
rust-lang-nursery/rustup.rs#1294 added a 'proxy' executable for the default path that will (once bundled rustfmt hits a channel) run the appropriate version for the default toolchain.

As such, it seems like the best option as of now is to remove the test for `rustup` and the alternate run entirely, and rely on whatever `rustfmt` is on the PATH: Anyone using nightly should (with minor setup) get the nightly version run, and once the new rustfmt hits stable, this test will not need updated to accomodate.
