### ISSUE TITLE
Preprocessor constant #defines can overflow on embedded platforms with small integer types

### ISSUE THREAD

**Issue by dylanmckay** [rust-lang-nursery/rust-bindgen#1185]
Some architectures have small integer types such as AVR, which has 16-bit `int`.

For preprocessor constants, bindgen emits the constant in Rust as a constant with type `libc::c_int`. If `c_int` is `i16`, large constants can overflow, causing compiler warnings.

This is a pretty obscure bug because it only appears on esoteric platforms with a small int type. At some point bindgen _could_ be modified so that it detects constant overflow and promotes to the next bigger integer type.

### Input C/C++ Header

```C++
#define NTP_OFFSET 3155673600
#define UNIX_OFFSET 946684800
```

### Actual Results

```rust

warning: literal out of range for u16
   --> src/bindings.rs:162:48
    |
162 | pub const UNIX_OFFSET: ::rust_ctypes::c_uint = 946684800;
    |                                                ^^^^^^^^^

warning: literal out of range for u16
   --> src/bindings.rs:163:47
    |
163 | pub const NTP_OFFSET: ::rust_ctypes::c_uint = 3155673600;
    |                                               ^^^^^^^^^^

warning: literal out of range for u16
   --> src/bindings.rs:864:53
    |
864 | pub const __AVR_LIBC_DATE_: ::rust_ctypes::c_uint = 20150209;
```

### Expected Results

Bindgen maps the preprocessor defines to Rust constants which have types large enough to fit the integer literal.

**Comment by emilio** [comment]
Huh, interesting, I'd have bet that we mapped them to actual fixed-sized types.

You can workaround it with ParseCallbacks. This can also be trivially fixed in var.rs, where the type is chosen. It's late for me now, but I'm happy to mentor or take a look tomorrow.

**Comment by emilio** [comment]
#1246
