### ISSUE TITLE
C++ template with const errro

### ISSUE THREAD

**Issue by drewkett** [rust-lang-nursery/rust-bindgen#1192]
This is a reduced case from a library that pulls in math.h on MacOS. It looks somewhat similar to #1051 and #798, but I thought I'd open another issue in case it helps.

### Input C/C++ Header

```C++
template <class _Tp, _Tp> struct a { static const _Tp value; };
template <class _Tp, _Tp b> const _Tp a<_Tp, b>::value = b;
```
 
This is another variation on it that generates the same error, without the second template parameter.

```C++
template <class _Tp> struct a { static const _Tp value; };
template <class _Tp> const _Tp a<_Tp>::value = 0;
```

### Bindgen Invocation

```
$ bindgen input.h -- -x c++
```

### Actual Results

```rust
extern "C" {
    pub static mut value: _Tp;
}
```

```
error[E0412]: cannot find type `_Tp` in this scope
 --> dummy.rs:4:27
  |
4 |     pub static mut value: _Tp;
  |                           ^^^ not found in this scope
```

### Expected Results

I don't know rust well enough to know how/if these templates can be translated into rust, but presumably this error could be avoided.

**Comment by fitzgen** [comment]
Thanks for filing an issue!

This is almost exactly identical to https://github.com/rust-lang-nursery/rust-bindgen/issues/798#issuecomment-329678006 so I'll close it in favor of that.

Your intuition to err on the side of "file an issue" is the right choice IMO!
