### ISSUE TITLE
Pure virtual functions generate bogus link_name.

### ISSUE THREAD

**Issue by jpathy** [rust-lang-nursery/rust-bindgen#1197]
Hello,
I am using bindgen to generate code from C++ headers and if i disable name mangling the resulting link_name for functions just become `function_name`, but the library symbols are of form `someprefix_classname_function_name`.  I am assuming it's a bit of namespace issue. Is there any way to achieve this?

**Comment by emilio** [comment]
Can you put an example? In general disabling name mangling is only supported to workaround old clang bugs in C, like #528.

**Comment by jpathy** [comment]
I am using steamworks sdk. Here is some snippet of a header file.

    class ISteamUser
    {
    public:
		virtual HAuthTicket GetAuthSessionTicket( void *pTicket, int cbMaxTicket, uint32 *pcbTicket ) = 0;
    }

Here is the relevant generated rust code. It fails to link with test program.

    #[repr(C)]
    pub struct ISteamUser__bindgen_vtable(::std::os::raw::c_void);
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct ISteamUser {
        pub vtable_: *const ISteamUser__bindgen_vtable,
    }
    extern "C" {
        #[link_name = "\u{1}GetAuthSessionTicket"]
        pub fn ISteamUser_GetAuthSessionTicket(
            this: *mut ::std::os::raw::c_void,
            pTicket: *mut ::std::os::raw::c_void,
            cbMaxTicket: ::std::os::raw::c_int,
            pcbTicket: *mut root::uint32,
        ) -> root::HAuthTicket;
    }

If i inspect the supplied library with the sdk.

    $ nm ~/Downloads/sdk/redistributable_bin/linux64/libsteam_api.so |grep GetAuthSession
    0000000000021f70 T SteamAPI_ISteamGameServer_GetAuthSessionTicket
    000000000001f810 T SteamAPI_ISteamUser_GetAuthSessionTicket

**Comment by emilio** [comment]
Oh ok, so the problem here is two. First of all we generate a link name for a pure virtual method, which is wrong. Then there's the long-standing problem that we don't support generating vtables properly, because of C++ compiler differences.

Let's fix the first one since at least that will fix the linking error.

**Comment by emilio** [comment]
#1199
