### ISSUE TITLE
Conflicting constified module enum/rustified enum regex leads to compile error when C enum has non-unique discriminant values

### ISSUE THREAD

**Issue by tmfink** [rust-lang-nursery/rust-bindgen#1198]
### Input C/C++ Header

```C
typedef enum MyDupeEnum {
	A = 0,
	A_alias = 0,
	B,
} MyDupeEnum;
```

### Bindgen Invocation

```
$ bindgen input.h test-constify-mod-enum.h --rustified-enum '.*' "--constified-enum-module" ".*"
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub const MyDupeEnum_A_alias: MyDupeEnum::Type = MyDupeEnum::A;
#[repr(u32)]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum MyDupeEnum {
    A = 0,
    B = 1,
}
```

and/or

```
error[E0223]: ambiguous associated type
 --> /tmp/a.rs:3:31
  |
3 | pub const MyDupeEnum_A_alias: MyDupeEnum::Type = MyDupeEnum::A;
  |                               ^^^^^^^^^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<MyDupeEnum as Trait>::Type`

error: aborting due to previous error
```

### Expected Results

 There are several possibilities for correct behavior:

1. Error out immediately because regex passed to `--rustified-enum`/`--constified-enum-module` overlap.
2. Define the precedence of enum strategies (rustified, constified module, and constified).
3. Support a more complete way for users to convey what enum strategy is used for a given enum. For example, bindgen could take a callback or struct that implements a `ConveysEnumStrategy` trait).
4. Whichever regex is passed first has precedence (the order of arguments/builder pattern calls matters). This would complicate the internal bindgen logic.

**Example of behavior 2:**
```rust
/* automatically generated by rust-bindgen */

#[repr(u32)]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum MyDupeEnum {
    A = 0,
    A_alias = 0,
    B = 1,
}
```

**Comment by fitzgen** [comment]
Thanks for the bug report @tmfink !

I think we should define a precedence and go with that.

**Comment by tmfink** [comment]
When can we expect a new `bindgen` release? I want to release a new version of [`capstone-sys`](https://github.com/capstone-rust/capstone-sys) that takes advantage of these bug fixes.

**Comment by tmfink** [comment]
Thanks!
