### ISSUE TITLE
Ability to generate variables with type usize/isize

### ISSUE THREAD

**Issue by michaeleiselsc** [rust-lang-nursery/rust-bindgen#1201]
I'd like to be able to generate types usize or isize. For example, for iOS and OSX, we have the commonly used NSUInteger and NSInteger types that map to usize and isize respectively. This is done with the following macro:
```
#if __LP64__ || (TARGET_OS_EMBEDDED && !TARGET_OS_IPHONE) || TARGET_OS_WIN32 || NS_BUILD_32_LIKE_64
typedef long NSInteger;
typedef unsigned long NSUInteger;
#else
typedef int NSInteger;
typedef unsigned int NSUInteger;
#endif
```

So what ends up happening is that bindgen ends up picking the specific type for the architecture that was passed to bindgen's clang command. Is there some way to deal with this? Thanks.

**Comment by emilio** [comment]
You can `blacklist_type("NSInteger")` and `blacklist_type("NSUInteger")`, then `raw_line("type NSInteger = isize; type NSUInteger = usize;")`.

Would that do the job? I can't think of a generic way of doing that.

**Comment by michaeleiselsc** [comment]
yes, thanks!

**Comment by emilio** [comment]
Ok then, thanks for filing! If you think documentation is lacking for this, a PR would be appreciated! :)
