### ISSUE TITLE
the trait bound `Align: std::marker::Copy` is not satisfied

### ISSUE THREAD

**Issue by helloqirun** [rust-lang-nursery/rust-bindgen#1203]
I am using this script https://gist.github.com/fitzgen/187381e358f60efa8194d0b276b4d11a.

I am using bindgen version 0.32.1 with hashtag 04591f0 .

$ ./b.sh bindgen abc.h
```
clang-4.0: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Error { repr: Custom(Custom { kind: Other, error: StringError("Cannot find binary path") }) }
error[E0277]: the trait bound `Align: std::marker::Copy` is not satisfied
  --> /tmp/bindings-KZJk5s.rs:10:5
   |
10 |     align: [Align; 0],
   |     ^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `Align`
   |
   = help: consider adding a `where Align: std::marker::Copy` bound
   = note: required because of the requirements on the impl of `std::clone::Clone` for `[Align; 0]`
   = note: required by `std::clone::Clone::clone`

error: aborting due to previous error

Interesting: bindgen emitted Rust code that won't compile!
```

$ cat abc.h
```c
struct a {
  int : 1;
};
```

**Comment by fitzgen** [comment]
Looks like something to do with our analysis of when we can derive copy or not combined with anonymous bitfields.

Thanks for filing an issue @helloqirun !

**Comment by emilio** [comment]
I can't repro this fwiw.

**Comment by emilio** [comment]
I suspect it's the same issue as #1202. I've tried both with current stable and nightly rust and it generates working code, so does `--rust-target 1.0`. Thanks for the report though!

**Comment by Eroc33** [comment]
Just came across this. The generated code is fine on stable and nightly, however for rust version 1.20.0 and before this issue appears, so --rust-target 1.0 and --rust-target 1.19 aren't actually compatible with those versions.
