### ISSUE TITLE
Fix licensing issue

### ISSUE THREAD

**Issue by glyn** [rust-lang-nursery/rust-bindgen#1206]
The contents of issue-816.h are covered by a license incompatible with bindgen's 3-clause BSD license. (With the benefit of hindsight, I should have pointed out this problem when I raised issue 816.)

**Comment by glyn** [comment]
@emilio @fitzgen Please assign to me. Fix in https://github.com/rust-lang-nursery/rust-bindgen/pull/1207.

**Comment by emilio** [comment]
Fixed by #1207. Thanks @glyn!

**Comment by glyn** [comment]
Thanks for wrestling with Travis @emilio!
