### ISSUE TITLE
Consider making a (patch?) release!

### ISSUE THREAD

**Issue by insaneinside** [rust-lang-nursery/rust-bindgen#1231]
Last release was just over a month ago, and there have been some bug fixes since then!    I'm certain I'm not the only person who would be very happy to see a patch release for those fixes. :smiley:

**Comment by emilio** [comment]
Yup, agreed! Let's wait for #1232 too so all reproduced regressions are gone :)

**Comment by emilio** [comment]
Bump running through CI now (#1233).
