### ISSUE TITLE
Opaque types do not honor no-* flags

### ISSUE THREAD

**Issue by osialr** [rust-lang-nursery/rust-bindgen#1238]
To preface, I'm just starting with bindgen so this could be me simply not thinking about the problem the right way in rust.

I have an allocator  function that returns an opaque type `MyTypeT`.  I would like the type to not have the `Copy` trait so that it's a move-only type. 

Neither the `--no-derive-copy` nor `--no-copy` flags affected the output of bindgen on the type.

### Input C/C++ Header
```C++
typedef struct MyType MyTypeT;
```

### Bindgen Invocation
```
$ bindgen --no-derive-copy --no-copy '.*' test.h -o out.rs
```

### Actual Results
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyType {
    _unused: [u8; 0],
}
pub type MyTypeT = MyType;
```

### Expected Results
```rust
#[repr(C)]
#[derive(Debug)]
pub struct MyType {
    _unused: [u8; 0],
}
pub type MyTypeT = MyType;
```

**Comment by emilio** [comment]
Yeah, I don't think these should be copy. Thanks for the report :)
