### ISSUE TITLE
Bindgen generates inconsistent enum representations on Windows and Unix

### ISSUE THREAD

**Issue by ebkalderon** [rust-lang-nursery/rust-bindgen#1244]
I am working on some [Rust bindings for RenderDoc](https://github.com/ebkalderon/renderdoc-rs), and I am trying to replace my hand-rolled FFI code with bindgen. However, I am running into an issue with incorrect and inconsistent enum representations between Windows and Unix-likes, where on Windows, the resulting code doesn't even compile when integrated into my bindings.

The bug is caused due to a single line in the input code below, and appears to be tangentially related to #1185.

### Input C/C++ Header

```C++
typedef enum {
  eRENDERDOC_Overlay_Enabled = 0x1,
  eRENDERDOC_Overlay_FrameRate = 0x2,
  eRENDERDOC_Overlay_FrameNumber = 0x4,
  eRENDERDOC_Overlay_CaptureList = 0x8,
  eRENDERDOC_Overlay_Default = (eRENDERDOC_Overlay_Enabled | eRENDERDOC_Overlay_FrameRate |
                                eRENDERDOC_Overlay_FrameNumber | eRENDERDOC_Overlay_CaptureList),
  eRENDERDOC_Overlay_All = ~0U, // <-- This is the culprit!
  eRENDERDOC_Overlay_None = 0,
} RENDERDOC_OverlayBits;

typedef uint32_t(RENDERDOC_CC *pRENDERDOC_GetOverlayBits)();
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Actual Results

On Unix, bindgen _correctly_ outputs:
```rust
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_Enabled: RENDERDOC_OverlayBits = 1;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_FrameRate: RENDERDOC_OverlayBits = 2;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_FrameNumber: RENDERDOC_OverlayBits = 4;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_CaptureList: RENDERDOC_OverlayBits = 8;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_Default: RENDERDOC_OverlayBits = 15;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_All: RENDERDOC_OverlayBits = 4294967295; // Technically correct value, but literal is out of range.
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_None: RENDERDOC_OverlayBits = 0;
pub type RENDERDOC_OverlayBits = u32; // Correct type.
pub type pRENDERDOC_GetOverlayBits = ::std::option::Option<unsafe extern "C" fn() -> u32>;
```

When cross-compiling on Unix to Windows, bindgen _incorrectly_ outputs:
```rust
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_Enabled: RENDERDOC_OverlayBits = 1;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_FrameRate: RENDERDOC_OverlayBits = 2;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_FrameNumber: RENDERDOC_OverlayBits = 4;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_CaptureList: RENDERDOC_OverlayBits = 8;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_Default: RENDERDOC_OverlayBits = 15;
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_All: RENDERDOC_OverlayBits = -1;  // Incorrect value!
pub const RENDERDOC_OverlayBits_eRENDERDOC_Overlay_None: RENDERDOC_OverlayBits = 0;
pub type RENDERDOC_OverlayBits = i32; // Incorrect type!
pub type pRENDERDOC_GetOverlayBits = ::std::option::Option<unsafe extern "C" fn() -> u32>;
```

### Expected Results

The correct enum representation in this case should have been `uint32_t` on both platforms. I would like to see better support for `~0U`/`u32::MAX` on the bindgen side of things.

**Comment by emilio** [comment]
Huh, interesting, which target are you passing to bindgen when cross-compiling? Afaict we just use the type that clang gives us.

**Comment by ebkalderon** [comment]
@emilio I'm cross-compiling to the `x86_64-pc-windows-msvc` target.

**Comment by emilio** [comment]
Sorry I couldn't look at this during the week. clang is returning us the signed integer type, instead of the unsigned one.

I think this is not a bindgen (nor clang) bug, and it's a bogus assumption that the enum ends up unsigned.

In particular, see https://godbolt.org/g/p6tBZP. MSVC is the only compiler that fails to compile that program, but passes if I replace `unsigned` with `int`.

I'm closing this because of the above, but please let me know if I got it wrong. Thanks a lot for the report! MSVC never stops to amuse me :)

**Comment by emilio** [comment]
For reference, just in case the godbolt link expires or something, the program is:

```cpp
#include <type_traits>

extern "C" {

typedef enum {
  eRENDERDOC_Overlay_All = ~0U,
} RENDERDOC_OverlayBits;

}

int main() {
  static_assert(
      std::is_same<std::underlying_type<RENDERDOC_OverlayBits>::type, unsigned>::value,
      "Huh");
}
```

**Comment by emilio** [comment]
It may be worth to point this up to upstream renderdoc, just in case it causes some weird behavior on windows.
