### ISSUE TITLE
Bindgen CLI crash on Windows

### ISSUE THREAD

**Issue by discosultan** [rust-lang-nursery/rust-bindgen#1254]
### System information

- Windows 10 x64
- clang version 5.0.1 (tags/RELEASE_501/final)
- cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
- rustc 1.25.0-nightly (4d2d3fc5d 2018-02-13)

### Bindgen Invocation

```
$ cargo install bindgen
$ bindgen --help
```

### Actual Results

```
---------------------------
bindgen.exe - System Error
---------------------------
The code execution cannot proceed because std-450236f2d0755271.dll was not found.
---------------------------
```

**Comment by Dushistov** [comment]
I suppose this is duplicate of #1248

**Comment by discosultan** [comment]
I found my answer from https://github.com/rust-lang-nursery/rust-bindgen/issues/1248 by @retep998:

> `bindgen` as a binary depends on internal rustc crates. Therefore you cannot run it directly, but instead must run it using `rustup run` and you must specify the same toolchain that you used to install it originally. If you ever update that toolchain then you must reinstall `bindgen`.
