### ISSUE TITLE
bindgen build error

### ISSUE THREAD

**Issue by Galigator** [rust-lang-nursery/rust-bindgen#1275]
Hello thank you for your work.
I am facing the build error problem in a tool that use _bindgen_ (https://github.com/snipsco/snips-nlu-rs).
Looking at the errors I show that the following commands results in a build failure :

```
git clone https://github.com/rust-lang-nursery/rust-bindgen.git
cd rust-bindgen
cargo build

```

The errors of the build failure are in the attach file.
[bindgen-build-time-error.txt](https://github.com/rust-lang-nursery/rust-bindgen/files/1810224/bindgen-build-time-error.txt)

The version of rustc is 1.21.0, the default of ubuntu xenial (there is no exact version specifiy in .travis.yml)

How _bindgen_ should be build ?

**Comment by emilio** [comment]
So this is from #1269, you can probably check out an older revision and it'll work.

But I don't think we guarantee to build with whatever version is the default in ubuntu. We guarantee to build with the latest stable rust.

This is what we use to test bindgen:

  https://github.com/rust-lang-nursery/rust-bindgen/blob/22041e13d08dbd4cb0ea777fa540897735d9e7c2/.travis.yml#L7

Thanks for the report!

**Comment by Galigator** [comment]
Thank for your time Emilio I will watch that.

**Comment by Galigator** [comment]
Using the lastest nightly the compilation work.
