### ISSUE TITLE
Regression of PR #916

### ISSUE THREAD

**Issue by stouset** [rust-lang-nursery/rust-bindgen#1304]
https://github.com/rust-lang-nursery/rust-bindgen/pull/916 regressed due to the changes in https://github.com/rust-lang-nursery/rust-bindgen/pull/915. Specifically, due to [`eeec4bd`](https://github.com/rust-lang-nursery/rust-bindgen/commit/eeec4bd2a197bb0ed71419f0700a93d418f6899a#diff-abe49f934e63fd596ce955feb78cdb08L836).

**Comment by emilio** [comment]
Indeed. If this is still interesting to somebody I'm happy to rubber-stamp a patch to reland that.
