### ISSUE TITLE
Virtual method problem

### ISSUE THREAD

**Issue by hg2ecz** [rust-lang-nursery/rust-bindgen#1309]
If I use virtual methods in C++ code, the bindgen forget to generate any rows. And here is one row with bad parameters: Example_Get(this: *mut ::std::os::raw::c_void ).

### Input C++ Header

```C++
class Example {
    public:
        Example(const char *s);
        virtual char *Get();
        virtual ~Example();
    private:
        char s[200];
        int counter=0;
};
```
Manually correction:
```diff
--- cpp_example-generated.rs  2018-05-05 01:21:01.251896746 +0200
+++ cpp_example_repaired.rs     2018-05-05 01:24:18.049910007 +0200
@@ -1,4 +1,4 @@
-/* automatically generated by rust-bindgen */
+/* generated by rust-bindgen and manually repaired */
 
 #[repr(C)]
 pub struct Example__bindgen_vtable(::std::os::raw::c_void);
@@ -47,15 +47,23 @@
 }
 impl Example {
     #[inline]
+    pub unsafe fn Get(&mut self) -> *mut ::std::os::raw::c_char {
+        Example_Get(self)
+    }
+    #[inline]
     pub unsafe fn new(s: *const ::std::os::raw::c_char) -> Self {
         let mut __bindgen_tmp = ::std::mem::uninitialized();
         Example_Example(&mut __bindgen_tmp, s);
         __bindgen_tmp
     }
+    #[inline]
+    pub unsafe fn destruct(&mut self) {
+        Example_Example_destructor(self)
+    }
 }
 extern "C" {
     #[link_name = "\u{1}_ZN7Example3GetEv"]
-    pub fn Example_Get(this: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_char;
+    pub fn Example_Get(this: *mut Example) -> *mut ::std::os::raw::c_char;
 }
 extern "C" {
     #[link_name = "\u{1}_ZN7ExampleD1Ev"]
```

**Comment by emilio** [comment]
That manual correction is wrong. If it's virtual it can get overriden by a subclass, and thus calling the method would call the subclass method. Your manual correction doesn't do that. Similar for the destructor. That's why bindgen doesn't do it.

Generating vtables and virtual methods properly is #27.

**Comment by hg2ecz** [comment]
Thank you, I was tired at the night, so I maked non-virtual call and I was happy, because my example code gave a good result for me. Thanks for correction.
But I have a question: how I can use the generated Example_Get() method from Rust?
If non virtual, it's easy:
```rust
fn get(obj: &mut cpp_example::Example) -> String {
    unsafe { CStr::from_ptr( obj.Get() ).to_string_lossy().into_owned() }
}
```

**Comment by emilio** [comment]
I don't think there's a good way of doing that except wrapping the virtual function call in a C function. That is, on top of your library, you'd need to compile something like the following C++:

```c
extern "C" char* MyObject_Get(Example* obj)
{
   return obj->Get();
}
```

I know it's somewhat annoying though :/

**Comment by mutantbob** [comment]
I have been wrapping the virtual function call in a C function as well.  It is totally annoying, especially when the number of virtual functions exceeds 1 dozen.

It's almost like we need a helper to `bindgen` that writes the C wrappers for us...  At least until they solve #27 ?
