### ISSUE TITLE
bindgen generates a static mut where a const is expected

### ISSUE THREAD

**Issue by alex** [rust-lang-nursery/rust-bindgen#1316]
### Input C/C++ Header

```C++
#define __GFP_IO                0x40u
#define GFP_KERNEL (__GFP_IO)

const unsigned BINDING_GFP_KERNEL = GFP_KERNEL;
```

### Bindgen Invocation
```
$ bindgen t.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub const __GFP_IO: u32 = 64;
pub const GFP_KERNEL: u32 = 64;
extern "C" {
    #[link_name = "\u{1}BINDING_GFP_KERNEL"]
    pub static mut BINDING_GFP_KERNEL: ::std::os::raw::c_uint;
}
```

### Expected Results

I expected `BINDING_GFP_KERNEL` to be generated as `pub const BINDING_GFP_KERNEL = ...`

**Comment by emilio** [comment]
Which versión of libclang is this using? I'd expect clang 4.0+ to generate the expected results

**Comment by alex** [comment]
wontfix per discussion on IRC

**Comment by WiSaGaN** [comment]
Any detailed explanation for the won't fix? Was it the use of a wrong `libclang`?

**Comment by geofft** [comment]
Yes. From my IRC logs, Alex was asked, "which libclang version are you using? Clang <= 3.9 doesn't offer APIs to resolve the actual values of constants, so we fall back to the following most likely thing to work which isn't really that great," to which he replied 3.8 and said using a newer version from https://apt.llvm.org fixed the bug. (If you're on Debian/Ubuntu, apt.llvm.org is a reasonable place to get things and is run by the same folks who package LLVM in Debian.)
