### ISSUE TITLE
bindgen after v0.35 hangs on x86_64 Windows llvm v6.0.0.20180508 from choco

### ISSUE THREAD

**Issue by spease** [rust-lang-nursery/rust-bindgen#1323]
### Input C/C++ Header
Cannot provide this (proprietary)

### Bindgen Invocation
```
bindings
    .header()
    ...
    .link()
    .generate()
    .expect()
    .write_to_file
    .expect()
```

### Actual Results

cargo hangs "forever" (as long as I've tried it, tens of minutes)

### Expected Results
cargo taktes ~7-8 seconds with bindgen 0.35

**Comment by emilio** [comment]
This is not really actionable as it stands... Could you maybe reduce the header with creduce, or bisect the issue to a bindgen revision, so that we can figure this out? Thanks!

**Comment by spease** [comment]
I'm not convinced that this is related to bindgen now - I think it's just a coincidence. The problem went away after I disabled RLS in Sublime.
