### ISSUE TITLE
Feature request: blacklist functions?

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang-nursery/rust-bindgen#1336]
At the moment, bindgen can blacklist types but not functions and constants. It might be nice to allow that (e.g. to be able to blacklist functions where Rust doesn't support the ABI).

**Comment by gnzlbg** [comment]
This is really necessary since currently `blacklisting` a type will still generate bindings for functions that use the type ... Without a way to black list them manually, nothing works. And having to blacklist everything by default and then white list stuff is extremely annoying.
