### ISSUE TITLE
Bitfields broken for big-endian machines.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#1340]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1462623

**Comment by psumbera** [comment]
Per: https://en.wikipedia.org/wiki/Bit_numbering  SPARC uses "LSB 0" bit numbering (the same as Little-endian CPUs).

So the proposed change is probably not needed. But something else is wrong...

I'm confused about:

https://github.com/rust-lang-nursery/rust-bindgen/blob/master/bindgen-integration/src/lib.rs#L223
```

        _bitfield_1: bindings::bitfields::First::new_bitfield_1(1, 2, 3)
    };
    assert!(unsafe {
first.assert(1, 2, 3)
```

---

What does mean value 3? This is 2 bytes row!

**Comment by emilio** [comment]
The bitfield has three named fields:

https://github.com/rust-lang-nursery/rust-bindgen/blob/0176a76fbfc861c70f7e93289c1c114de16e7282/bindgen-integration/cpp/Test.h#L60

**Comment by psumbera** [comment]
With following all test passes on both sparc and intel:

https://github.com/rust-lang-nursery/rust-bindgen/pull/1342

(though I haven't verified Firefox yet)
