### ISSUE TITLE
__attribute__((overloadable)) function has wrong name

### ISSUE THREAD

**Issue by bobbobbio** [rust-lang-nursery/rust-bindgen#1350]
### Input C Header

```C
void
my_function(int a)
    __attribute__((overloadable));

void
my_function(const char *a);
```

### Bindgen Invocation
```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}_Z11my_functioni"]
    pub fn my_function(a: ::std::os::raw::c_int);
}
extern "C" {
    pub fn my_function1(a: *const ::std::os::raw::c_char);
}
```

### Expected Results

Normally bindgen gets things correct with the overloadable attribute, but in this specific case (when overloadable comes first followed by a function without it), the second function has the wrong name, and the binding doesn't work.

**Comment by emilio** [comment]
Yeah, we do `if mangled_name == function_name { mangled_name = None }` before doing the times_seen mangling, so I can see this breaking.

Should be pretty easy to fix though, thanks for the report!

**Comment by emilio** [comment]
Hmm, fwiw, that testcase in some compilers it complains hard:

> tests/headers/issue-1350-attribute-overloadable.h:2:6: error: overloaded function 'my_function' must have the 'overloadable' attribute, err: true
