### ISSUE TITLE
Odd behavior generating clang arguments

### ISSUE THREAD

**Issue by joshlf** [rust-lang-nursery/rust-bindgen#1352]
I've discovered odd behavior with how `bindgen` generates flags to pass to clang. In particular, I added a `println!` [here](https://github.com/rust-lang-nursery/rust-bindgen/blob/d61ab759e3512d79131eb6c455862915c6b6c4d2/src/ir/context.rs#L558) to print the `clang_args` variable.

### Bindgen Invocation and Results

Here are three different invocations of `bindgen` along with the value of `clang_args` that was printed as a result:

- `bindgen bindgen.h`
  - `["--target=x86_64-apple-darwin", "-isystem", "/Library/Developer/CommandLineTools/usr/include/c++/v1", "-isystem", "/usr/local/include", "-isystem", "/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include", "-isystem", "/Library/Developer/CommandLineTools/usr/include", "-isystem", "/usr/include", "-isystem", "/System/Library/Frameworks", "-isystem", "/Library/Frameworks", "bindgen.h"]`
- `bindgen bindgen.h -- -I foo`
  - `["--target=x86_64-apple-darwin", "-I", "foo", "-isystem", "/Library/Developer/CommandLineTools/usr/include/c++/v1", "-isystem", "/usr/local/include", "-isystem", "/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include", "-isystem", "/Library/Developer/CommandLineTools/usr/include", "-isystem", "/usr/include", "-isystem", "/System/Library/Frameworks", "-isystem", "/Library/Frameworks", "bindgen.h"]`
- `bindgen bindgen.h -- -foo bar`
  - `["--target=x86_64-apple-darwin", "-foo", "bar", "bindgen.h"]`
- `bindgen bindgen.h -- --target=foo`
  - `["--target=foo", "bindgen.h"]`

### Expected Results

Unrecognized flags such as `-foo` shouldn't affect other flags that are passed, such as `-isystem`. I'm not sure whether `--target` altering what flags are passed is intentional; at the least, `bindgen` seems smart enough to realize that the `--target` argument should replace the default `--target=x86_64-apple-darwin`.

I found this while debugging https://github.com/rust-lang-nursery/rust-bindgen/issues/1331, and I suspect that they may be related.

**Comment by joshlf** [comment]
Ah, that's a shame. Oh well. I understand the limitations, though.

**Comment by emilio** [comment]
Alright, closing then.

Note that there's #297 to consider moving away from libclang, which presumably would allow us to get better error information... But that's a bigger undertaking as well :)
