### ISSUE TITLE
blacklisting a type does not ignore functions with the type on their API/ABI

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-bindgen#1363]
### Input C/C++ Header

```C++
struct A {};
void foo(A a) { }
```

now blacklisting the type `A` will still generate bindings for `foo`, and there is no way to manually blacklist foo (see #1336 ).

**Comment by emilio** [comment]
I think this is expected behavior. Firefox at least uses `--blacklist-type` in order to replace some types with something more convenient from rust for example.

Fixing #1336 should've addressed this particular use case.
