### ISSUE TITLE
All backtick-quoted text in book goes on its own line

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rust-bindgen#1367]
Obviously this is highly undesirable in many cases. See e.g. https://rust-lang-nursery.github.io/rust-bindgen/cpp.html.

**Comment by mbrubeck** [comment]
If I remember correctly, this can happen when the browser has stylesheets (?) cached from an old version of the book.  Try holding down the shift key while reloading the page to clear the cache.

**Comment by alexreg** [comment]
Ah, well I noticed this is only a problem on Chrome (latest version). It views fine on Safari.

**Comment by emilio** [comment]
Yeah, this can happen when localStorage stores an item with the wrong value. `localStorage.setItem('theme', 'light')` should fix it for example.

**Comment by emilio** [comment]
I updated mdbook regardless since they added some workarounds for bogus localStorage stuff, in case it helps.

**Comment by alexreg** [comment]
@emilio Thanks!
