### ISSUE TITLE
Properly handle enum constants near u32::max_value()

### ISSUE THREAD

**Issue by nox** [rust-lang-nursery/rust-bindgen#1380]
https://github.com/servo/mozangle/blob/a0669cd1650447bbe699365306a34b451f350e1f/gfx/angle/checkout/include/GLSLANG/ShaderLang.h#L219

https://github.com/servo/mozangle/blob/18ce8502665eae603461f823ad5ad6c2dd31968e/src/shaders/bindings.rs#L80-L83

**Comment by emilio** [comment]
Should be able to fix this relatively easy with the APIs that were added in https://reviews.llvm.org/D26788.
