### ISSUE TITLE
Deriving PartialOrd and Ord for enum

### ISSUE THREAD

**Issue by tathanhdinh** [rust-lang-nursery/rust-bindgen#1395]
Hello all,

I'm trying to derive `Ord` and `PartialOrd` with bindgen

### Input C/C++ Header

```C++
enum A {
	a0 = 0,
	a1 = 1,
};
```

### Bindgen Invocation

```
bindgen test.h --with-derive-eq --with-derive-partialeq --with-derive-ord --with-derive-partialord --rustified-enum "A" > test.rs

```

### Actual Results

```
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum A {
    a0 = 0,
    a1 = 1,
}
```

### Expected Results

```
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum A {
    a0 = 0,
    a1 = 1,
}
```

I suppose that `ParitalOrd` and `Ord` would be included, but they are not.

**Comment by emilio** [comment]
Looks like we're only honoring the `derive_foo` in structs / unions. The `impl CodeGenerator for Enum` should be modified to honor them as well.

Should be an easy change, want to submit a patch? I'm happy to mentor or resolve any doubts that you could have :)

**Comment by tathanhdinh** [comment]
Hi @highfive: I want to take a try (though not familiar yet with bindgen), then `@highfive: assign me`.

**Comment by clouds56** [comment]
Similar issue here, should enum honor `derive_debug(false)`?
