### ISSUE TITLE
rust-bindgen is not functional under Windows in my case (details inside)

### ISSUE THREAD

**Issue by barabadzhi** [rust-lang-nursery/rust-bindgen#1414]
I'm using the latest rust-bindgen release ```0.42.0``` to work with [this](http://rdf.bg/ifc-engine-dll.html) C library.

The 64 bit versions work fine on Linux and macOS, but crashes at runtime with
"Access violation reading location” error all the time on Windows (at least it builds without errors).

I decided to try out 32 bit Windows build, because of some wearied inconsistencies between the [library docs](http://rdf.bg/ifcdoc/CP64/sdaiOpenModelBN.html) and actual generated bindings code (int64 return type was mapped to i32:question:, happened only on Windows).

The Windows 32 build didn't even pass the linking phase.

```
OS: Windows 10 Pro 64 bit
clang version 7.0.0 (tags/RELEASE_700/final)
clang target: i686-pc-windows-msvc
rustc: 1.29.1 (b801ae664 2018-09-20)
cargo target: stable-i686-pc-windows-msvc
```

I created a public demo [github repo](https://github.com/barabadzhi/ifc-test) to help reproduce an issue.

### Actual Results

![screenshot from 2018-10-07 19-38-23](https://user-images.githubusercontent.com/8407846/46584843-a8129600-ca68-11e8-9b73-a682fca53bfd.png)

### Expected Results

Code compiles and prints something like

```bash
model handle: 140607394154904
```
at runtime (handle can be any number).

PS: ```src\ifcengine\vendor\ifcengine.dll``` should be manually dropped to ```target\debug``` to run an executable without missing library error (in case of linking phase susses).

PPS: If any feather info/tests are needed I'm happy to provide what I can. :construction_worker_man:
 
PPPS: Thanks for all the awesome work you do, guys! :slightly_smiling_face:

**Comment by emilio** [comment]
So, just to double-check (since I'm not really familiar with windows debugging).

Running `cargo test` on that crate should run a bunch of layout-related tests. I assume those all pass.

Looks like the open call is working, so what needs to be crashing is necessarily the close call.

What does `::std::mem::size_of::<IfcIntT>()` return? That's the only thing that I think could go wrong in this example.

**Comment by emilio** [comment]
Oh, you mentioned it had the wrong size here:

> int64 return type was mapped to i32

So yeah, that's a bug, but it's not clear to me it's a bindgen bug. It's probably a bug in the headers or in the target passed to bindgen.

The header contains:

```c

#if defined(WIN64) || defined(__LP64__)
	typedef int64_t int_t;
#ifndef __ANDROID__
	typedef uint64_t uint_t;
#endif
#else
	typedef int32_t int_t;
#ifndef __ANDROID__
	typedef uint32_t uint_t;
#endif
#endif
```

It should be possible to add another type into that ifdef and see that bindgen is not seeing it.

I _think_ the `if defined(WIN64)` should really be `if defined(_WIN64)`.

**Comment by barabadzhi** [comment]
Hi, @emilio

Indeed, as I said: ```::std::mem::size_of::<IfcIntT>()``` yields ```4 bytes``` on 64 bit build.

But, correcting vendor headers did the trick!

Running  fine on all OSes now. :information_source: 

The last thing you'll think is that your vendor give you a :bug: :gift: :smile: 

I'm closing this, thank you! :clap:
