### ISSUE TITLE
Use debugging information to assert that generated layouts/signatures are correct

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#151]
This would be a huge boost to my confidence in our correctness and ability to identify and catch bugs in our test suite.

Here is a sketch of what I'm imagining:
1. Compile C/C++ header file into an object file.
2. Generate and compile Rust bindings for the C/C++ header file.
3. Read the debugging information for the object file and get the layout of structs/unions and function signatures.
4. Read the debugging information for the compiled Rust bindings and get the layout of generated structs/unions and function signatures.
5. Compare (3) and (4) and assert that they match up with each other.

We can use `gimli` for reading DWARF on unix; we would need some PDB library for Windows. I think it might be practical/pragmatic to start with just unix.

Eventually, we could even drive this process with Csmith.

**Comment by emilio** [comment]
Note that we generate `#[test]` functions for struct size and alignment already.

**Comment by fitzgen** [comment]
Yes, those tests are valuable and have caught bugs for me in the wild before.

However, that is based on our own understanding of the layout. If our understanding is wrong due to a bug, we can generate incorrect `#[test]`s which may incorrectly pass. For example, if we generate bindings with different defines from how the C/C++ was compiled, bindgen's runtime view of layout and the generated bindings' `#[test]` view of layout will agree, but the compiled code's *actual* layout can differ (I have also hit *this* bug, and the existing `#[test]`s did *not* catch it).

The debugging information for the object file is used by many different consumers (gdb, perf, valgrind, etc) and has existed for a long time, so it is very reliable.

**Comment by fitzgen** [comment]
Working on this.

**Comment by fitzgen** [comment]
I don't think this is actually worth it.

It's not like we're calculating our own layouts, we're just piping through what `libclang` gives us, which is the same as what `clang` is going to put into the debug info.
