### ISSUE TITLE
Provide support for C functional macros

### ISSUE THREAD

**Issue by Slabity** [rust-lang-nursery/rust-bindgen#231]
Some C macros make heavy use of functional macros to produce values, such as the `_IO*` family of macros for producing numbers for `ioctl`

It would be nice if bindgen could evaluate these as well.

**Comment by emilio** [comment]
Yup, agreed. This is probably more a request for `cexpr`, I guess, which is the crate we use for evaluating macros.

**Comment by emilio** [comment]
There's a bit more discussion in #753, so closing as a dupe.
