### ISSUE TITLE
We could be smarter about implementing Copy/Clone

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#56]
Testcase:

``` cpp
template<typename T>
struct Foo {
    char bar[50];
};
```

vs.

``` cpp
struct Foo {
    char bar[50];
};
```

We're conservative here, but we could be smarter if we know the struct has no template parameters, since all the arrays (even the big ones) implement magically `Copy`, so we can do:

``` rust
impl Clone for MyStruct { fn clone(&self) -> Self { *self } }
```

But this wouldn't work for templated structs, where we `derive` it.

**Comment by WiSaGaN** [comment]
Struct like `struct Foo { char bar[81]; };` used to have `Copy` derived with `Clone` manually implemented using `Copy` described in the OP. This is at least true in `bindgen` 0.16. This is blocking me to upgrade `bindgen`...
