### ISSUE TITLE
Automatically allow `non_snake_case, non_camel_case_types, non_upper_case_globals`

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rust-bindgen#562]
Bindings generated by bindgen are not expected to follow Rust naming conventions, so it's a reasonable default to automatically add `#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]` to the generated module.

**Comment by fitzgen** [comment]
See also #373

**Comment by framlog** [comment]
@highfive: assign me

**Comment by jdm** [comment]
Have you made any progress, @framlog? Any questions?

**Comment by jdm** [comment]
Oh, I missed #580.

**Comment by framlog** [comment]
@jdm It should works imo.

**Comment by emilio** [comment]
I don't think we should do that given how invasive it is (see #580). Thanks @framlog, though, for coming up with a PR!
