### ISSUE TITLE
bindgen generates erroneous rust code: error: expected identifier, found `_`

### ISSUE THREAD

**Issue by Jackneill** [rust-lang-nursery/rust-bindgen#631]
See https://github.com/rust-lang-nursery/rust-bindgen/issues/631#issuecomment-318654881 and https://github.com/rust-lang-nursery/rust-bindgen/issues/631#issuecomment-328071187 for small, reproducible test cases.

------------------------------------------------------

Original bug report:

<details>

### Input C/C++ Header

wrapper/dae.h (https://github.com/rdiankov/collada-dom/blob/master/dom/include/dae.h):
```C++
#include <dae.h>
```

### Bindgen Invokation

```Rust
extern crate bindgen;

use std::env;
use std::path::Path;

fn main()
{
	let mut builder = bindgen::builder();
	let args = [
		"-x", "c++",
		"-std=c++11",

		"-DRUST_BINDGEN",

		"-I/usr/include/collada-dom2.4",
		"-includedae.h",

		"-DCOLLADA_DOM_SUPPORT141",
		"-DCOLLADA_DOM_SUPPORT150",
		"-DDEBUG=1",
	];
	for &arg in args.iter() {
		builder = builder.clang_arg(arg);
	}

	let out_dir = env::var("OUT_DIR").unwrap();
	builder = builder
		//.use_core()
		.enable_cxx_namespaces();

	let _ = builder.header("wrapper/dae.h")
		.generate().unwrap()
		.write_to_file(Path::new(&out_dir).join("dae.rs"));
}
```

### Actual Results

```
➜ cargo build
   Compiling colladadom v0.0.1-alpha (file:///home/jackneill/projects/colladadom-rs)
error: expected identifier, found `_`
     --> /home/jackneill/projects/colladadom-rs/target/debug/build/colladadom-7733e63caf1d0510/out/dae.rs:21379:18
      |
21379 |         pub type _ = u8;
      |                  ^
      |
      = note: `_` is a wildcard pattern, not an identifier
```

### Expected Results

No compilation errors.

</details>

**Comment by fitzgen** [comment]
Thanks for the bug report!

**Comment by emilio** [comment]
I and @Jackneill investigated this a bit, that seems to come from boost's mpl module (https://github.com/boostorg/mpl/blob/3b126bdf8c7abbfef27101232a379c8e0c3db1ac/include/boost/mpl/assert.hpp), so we're presumably messing some type or namespace there.

**Comment by fitzgen** [comment]
Easiest way forward would probably be to creduce that mpl header to find out exactly what is giving us problems: https://github.com/servo/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases

**Comment by Xaldew** [comment]
Hello,

I ran into this issue just a little while ago while trying to generate bindings for [Halide](http://halide-lang.org/). After some research in the header file, I noticed that a single underscore (`_`) is used as a variable in the `Halide` namespace.

As far as I can tell, this seems to be allowed by the C++ standard (at least according to [cppreference](http://en.cppreference.com/w/cpp/language/identifiers)). The caveat is that the variable (`_`) must be created outside of the global namespace.

This makes it rather easy to create a reduced example that triggers this:

`test.hpp`:

```c++
namespace rs_test
{

// This is a valid identifier outside the global namespace.
const int _ = 10;

int get_underscore()
{
    return _;
}

}
```

`build.rs`:

```rust
extern crate bindgen;

use std::env;
use std::path::PathBuf;


fn main()
{
    let bindings = bindgen::Builder::default()
        .header("test.hpp")
        .clang_args(["-x", "c++", "-std=c++11"].iter())
        .enable_cxx_namespaces()
        .generate()
        .expect("Unable to generate rust bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
```

**Comment by emilio** [comment]
Oh, ok, that's super-helpful, thanks!

**Comment by code-ape** [comment]
Hello,

I know this has already been reported but I just thought I'd add another occurrence report in case someone has the same issue as me. I've encountered this issue when trying to generate a binding of some Linux uapi headers, specifically any that include [`linux/include/uapi/linux/atmapi.h`](https://github.com/torvalds/linux/blob/v4.9/include/uapi/linux/atmapi.h) which has the following struct declaration:

```c
/*
 * Opaque type for kernel pointers. Note that _ is never accessed. We need
 * the struct in order hide the array, so that we can make simple assignments
 * instead of being forced to use memcpy. It also improves error reporting for
 * code that still assumes that we're passing unsigned longs.
 *
 * Convention: NULL pointers are passed as a field of all zeroes.
 */
 
typedef struct { unsigned char _[8]; } __ATM_API_ALIGN atm_kptr_t;
```

That results in the following Rust code:

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct atm_kptr_t {
    pub _: [::std::os::raw::c_uchar; 8usize],
}
```

And thus the cargo error:

```
error: expected identifier, found `_`
   --> src/linux/atm_tcp.rs:180:9
    |
180 |     pub _: [::std::os::raw::c_uchar; 8usize],
    |         ^
    |
    = note: `_` is a wildcard pattern, not an identifier
```

Anyways, keep up the awesome work! Bindgen is an amazing tool that I know will only continue to get better.

Thanks,
code-ape

**Comment by fitzgen** [comment]
I think all we need to do is add a new special case in the `rust_mangle` method in `src/ir/context.rs`. And a regression test.

Let me know if you're interested in picking up this issue!

**Comment by code-ape** [comment]
@fitzgen sure! I may not be able to get to it until next weekend, but I'll be happy to add this in. Should I tag myself with the HighFive system? I'm not familiar with it.

**Comment by fitzgen** [comment]
@code-ape cool! I'll mark the issue assigned (commenting `@highfive: assign me` just causes @highfive to add the `C-assigned` label).

Let me know if you run into any questions or anything!

**Comment by fitzgen** [comment]
lol :-P

**Comment by AndrewGaspar** [comment]
@highfive: assign me
