### ISSUE TITLE
Rewrite `can_derive_copy[_in_array]` as either a graph traversal or fix-point analysis

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#766]
See https://github.com/servo/rust-bindgen/issues/536 for details.

**Comment by fitzgen** [comment]
Note that in #767, we found it easier to compute the set of things that *cannot* derive `Debug` rather than the set of things that *can*.

**Comment by photoszzt** [comment]
I think this may involve two sets instead of one set. Named would not be the cannot_derive_copy set but it would be in the cannot_derive_copy_in_array set. Can the monotone framework return two sets instead of one?

**Comment by fitzgen** [comment]
> Can the monotone framework return two sets instead of one?

Yep!

**Comment by photoszzt** [comment]
@highfive assign me

**Comment by photoszzt** [comment]
Looks like highfive doesn't work. I'm working on this.
