### ISSUE TITLE
Rewrite `is_unsized` as a fix-point analysis

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#768]
See https://github.com/servo/rust-bindgen/issues/536 for details.

This is very similar to when we re-wrote `has_destructor` to a fixed-point analysis, and that PR could be used to guide fixing this issue: https://github.com/rust-lang-nursery/rust-bindgen/pull/850

**Comment by fitzgen** [comment]
@tz70s, this could be a good next issue for you to hack on :)

See #536 and also [this comment](https://github.com/servo/rust-bindgen/issues/765#issuecomment-312738735) for some details about the kinds of changes we'd like to make. The comments in `src/ir/analysis.rs` and `src/ir/named.rs` should also give some context.

Let me know if you want to take this, and I'll assign it to you! Also, don't hesitate to ask me any questions :)

**Comment by tz70s** [comment]
@fitzgen, sure, looks interesting, please assign it to me! 
I'll start to work on this in these two days, thanks!

**Comment by fitzgen** [comment]
Great! Let me know if you have any questions or run into any roadblocks, and I'll do my best to help :)

**Comment by tz70s** [comment]
Hi @fitzgen, I'm a little confused about what actually I should do for.
So the main purpose is to remove the recursive way in the `is_unsized` right?

i.e. in `src/ir/ty.rs`
```rust
pub fn is_unsized(&self, ctx: &BindgenContext) -> bool {
        debug_assert!(ctx.in_codegen_phase(), "Not yet");

        match self.kind {
            TypeKind::Void => true,
            TypeKind::Comp(ref ci) => ci.is_unsized(ctx),
            TypeKind::Opaque => self.layout.map_or(true, |l| l.size == 0),
            TypeKind::Array(inner, size) => {
                size == 0 || ctx.resolve_type(inner).is_unsized(ctx)
                // remove the recursive calls of is_unsized(ctx) into an another way?
            }
            // ...
``` 
and also in `src/ir/comp.rs`.

So we are going to use the graph traversal way already implemented in `src/ir/traversal.rs`?

**Comment by fitzgen** [comment]
> So the main purpose is to remove the recursive way in the is_unsized right?

Correct.

> So we are going to use the graph traversal way already implemented in src/ir/traversal.rs?

There are two options:

1. Replace the recursive `is_unsized` calls with an IR graph traversal. `src/ir/traversal.rs` provides the infrastructure needed to do a walk of the IR graph, or some subset of it, but it is up to us to use that infrastructure. This would end up looking something like:

```rust
pub fn is_unsized(&self, ctx: &BindgenContext, id: ItemId) -> bool {
    fn should_follow_edge(edge: Edge) -> bool {
        match edge.kind() {
            EdgeKind::Field | EdgeKind::BaseMember => true,
            _ => false,
        }
    }

    !ItemTraversal::new(ctx, std::iter::once(id), should_follow_edge).any(|id| {
        match ctx.resolve_type(id).kind() {
            // <insert trivially sized type kinds here>
            _ => false,
        }
    })
}
```

The downside is that if a `Burrito` contains a `Rice`, and a `Sushi` contains a `Rice`, and we ask if `Burrito` is unsized and if `Sushi` is unsized, we effectively compute whether `Rice` is unsized multiple times. The next option avoids this recomputation.

2. The second option is implementing a fix-point analysis that calculates the sized-or-unsized-ness of every whitelisted type up front before we enter codegen. For this approach, see https://github.com/servo/rust-bindgen/issues/765#issuecomment-312738735 for details.

**Comment by fitzgen** [comment]
@tz70s how's it going? Still working on this? Did I answer all your questions?

**Comment by tz70s** [comment]
@fitzgen Sorry I'm a little busy recently. I've traced code already, will do it this weekend!

**Comment by fitzgen** [comment]
Cool, no problems :) The code has shuffled around a tiny bit since we last talked: some of the other things from the meta issue were ported to fixpoint analyses, check out the `src/ir/analysis` mod and the files in there, they will serve as good templates to work from :)

**Comment by fitzgen** [comment]
@tz70s still hacking on this? Need any help getting unblocked or anything like that?

**Comment by fitzgen** [comment]
Unassigning due to inactivity.
