### ISSUE TITLE
Bitfield constructors may overflow the stack on codegen phase.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#775]
See this stack @Manishearth provided while building stylo:

https://gist.github.com/Manishearth/b1a99776beaf9a1c8bc3274bfc8293d0

I'm pretty sure it's because of one of our bitfield constructors growing a lot. @fitzgen mentioned on IRC he doesn't need `const fn` constructors anymore, so this can be greatly simplified into a linear sequence of expressions.

**Comment by fitzgen** [comment]
We no longer generate recursive bit operations for constructors.
