### ISSUE TITLE
Document bitfield usage in the users guide

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#818]
Similar to the section on using unions, we should have a section on using bitfields.

**Comment by ambaxter** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
@ambaxter I don't think we have anything in CONTRIBUTING.md about using `mdbook` yet (another PR opportunity!), but between [`mdbook`'s documentation](http://azerupi.github.io/mdBook/) and running `mdbook watch` from the `./book` directory, I think you should be able to figure everything out.

As far as content goes, we should just explain how bitfields get translated from C/C++ into Rust, and how to use them. You can experiment locally and look at the bitfield related tests. High bits are getters, setters, and bitfield unit constructors.

Let me know if you have any questions :)

**Comment by fitzgen** [comment]
@ambaxter making any progress here? Anything I can help with?

**Comment by ambaxter** [comment]
I am making some progress. A few things came up that took my time. Hope to be done in the next day or two.
