### ISSUE TITLE
Move repo to the rust-lang-nursery organization?

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#831]
This is something we've talked about off and on, but haven't centralized the discussion or come to any conclusions. So:

# Goals

* Attract more outside contributors and maintainers

# Questions

* Would we be able to carry our bots with us? Or would we switch to the rust org's bots?

cc @nrc @emilio

**Comment by nrc** [comment]
> Would we be able to carry our bots with us? Or would we switch to the rust org's bots?

I think you would keep your bots. They may need some URLs changing, but I suspect they won't need it because of GitHub's redirects.

**Comment by fitzgen** [comment]
I'm +1 on this.

@emilio wdyt?

**Comment by emilio** [comment]
Sounds good, as long as issues and similar stuff are preserved.

**Comment by fitzgen** [comment]
Resolved :)
