### ISSUE TITLE
Stop passing `whitelisted_items` as an argument to the codegen functions, and use ctx.codegen_items() instead.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#838]
This was computed on the fly before and passed as an argument. Now we precompute it in `context.rs`, and just pass `codegen_items()` as an argument.

We should be able to remove that argument altogether and just call `codegen_items` when needed, given we also pass the context pretty much everywhere.

**Comment by omakk** [comment]
@highfive: assign me

**Comment by jhod0** [comment]
Should this be closed?

**Comment by fitzgen** [comment]
Yes, thanks!
