### ISSUE TITLE
bors-servo doesn't seem to be working anymore

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#854]
eg https://github.com/rust-lang-nursery/rust-bindgen/pull/850#issuecomment-317905209

**Comment by fitzgen** [comment]
Seems not to have accepted the invite yet.

![bors-waiting](https://user-images.githubusercontent.com/74571/28598555-37df7dc6-7159-11e7-8c7d-516cfa17f4fb.png)

**Comment by KiChjang** [comment]
@larsbergstrom do you have to login as @bors-servo in order to accept the invitation?

**Comment by fitzgen** [comment]
Seems to still not be working: https://github.com/rust-lang-nursery/rust-bindgen/pull/855#issuecomment-318124297

**Comment by fitzgen** [comment]
https://github.com/rust-lang-nursery/rust-bindgen/pull/858#issuecomment-318214314
