### ISSUE TITLE
Emit a "manual" implementation of Debug when it cannot be derived

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#875]
Could initially just print the type's name as a placeholder.

Could eventually print the fields within the type that *are* `Debug` and placeholders for the fields that aren't.

Should be behind a new option.

**Comment by bkchr** [comment]
Can you point a place where to start looking?

**Comment by bkchr** [comment]
Ahh, I think I found [it](https://github.com/rust-lang-nursery/rust-bindgen/blob/d1d35007c0e2d085ae8fa4f81573e2f45ec95643/src/codegen/mod.rs#L1838) :)

**Comment by fitzgen** [comment]
@bkchr yep! Let me know if you have any other questions :)

**Comment by bkchr** [comment]
I use cargo test --features testing_only_libclang_4 to run the tests. Is it normal that the expectation files are modified by the test case? 
Are there also some tests that try to compile the generated rust files?

**Comment by bkchr** [comment]
Okay, I answered the question myself. ^^
Using cd tests/expectations && cargo test, compiles and tests the generated files.

**Comment by fitzgen** [comment]
> Is it normal that the expectation files are modified by the test case?

Yes, this is to make it easier to update test expectations when making changes that modify their output, and its easy enough to `git checkout -- tests/expectations` to remove the modifications if they're undesired.

> Are there also some tests that try to compile the generated rust files?

Yeah, I had thought this was documented in `CONTRIBUTING.md`, but it doesn't seem to be. I need to fix that.

**Comment by bkchr** [comment]
It is documented in the Contribution.md, but the command, written there, does not work. Or at least did not worked for me ^^

**Comment by bkchr** [comment]
I think that can now be closed @fitzgen ?

**Comment by fitzgen** [comment]
Yes, thanks! Were you interested in hacking on some other bindgen issues? We have plenty, if you're looking :)
