### ISSUE TITLE
"manually" implement PartialEq when it cannot be derived

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#879]
Depends on https://github.com/rust-lang-nursery/rust-bindgen/issues/878.

We should be conservative and only implement this when the reason we cannot derive is because we're hitting the array length derive limit and similar easy cases. We can't know all the corner cases for types we have no knowledge of, and we shouldn't try.

**Comment by pepyakin** [comment]
@highfive: assign me
