### ISSUE TITLE
Derive PartialOrd when possible

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#882]
~~Should be very similar to deriving Default, see `src/ir/analysis/derive_default.rs` and the `CanDeriveDefault` trait that gets used in codegen.~~

Easier than this, see https://github.com/rust-lang-nursery/rust-bindgen/issues/882#issuecomment-330317036 below.

**Comment by photoszzt** [comment]
Looking at the definition of PartialOrd, if you can implement PartialEq you should be able to implement PartialOrd.

**Comment by fitzgen** [comment]
> @fitzgen Looking at the definition of PartialOrd, if you can implement PartialEq you should be able to implement PartialOrd.

(Somehow missed this comment when it was originally posted)

This insight should make it rather easy to implement this functionality then :)

I think we can just rename the analysis from `cannot_derive_partialeq` to `cannot_derive_partialeq_or_partialord` (and other relevant names) and then all we have to do is add the new members to `BindgenOptions` and `Builder` to track whether the user has requested deriving `PartialOrd`, and in `src/codegen/mod.rs` where we emit the `derive(...)` bits, check the same results as we do for `PartialEq` when emitting `PartialOrd`.

**Comment by pepyakin** [comment]
@highfive: assign me
