### ISSUE TITLE
Rename `TypeKind::Named` to `TypeKind::TypeParam`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#914]
And anywhere we refer to "named" types, we should start referring to "type parameters".

If you want to pick this up, just drop a comment :)

I suggest starting by reading CONTRIBUTING.md and running the tests locally, then diving right into this bug.

**Comment by anna-liao** [comment]
@highfive: assign me

**Comment by anna-liao** [comment]
I'm interested in working on this issue.  I followed the contributing.md and it build ok, but a few tests failed when I ran `cargo test`.

failures:
    header_auto_hpp
    header_const_bool_hpp
    header_constant_evaluate_h
    header_issue_769_bad_instantiation_test_hpp
    header_objc_template_h
    header_partial_specialization_and_inheritance_hpp
    header_type_alias_template_specialized_hpp

test result: FAILED. 339 passed; 7 failed; 0 ignored; 0 measured

It may be specifying the path for libclang.  How do I find the path for libclang on Mac OS?

@highfive: assign me

**Comment by fitzgen** [comment]
Hi @anna-liao ! Can you try following the instructions here for getting libclang >= 3.9? https://rust-lang-nursery.github.io/rust-bindgen/requirements.html#clang

I think you can pretty much `brew install llvm` and then set the `LIBCLANG_PATH=/usr/local/Cellar/...` env var to the directory where the `libclang.dylib` resides.

**Comment by fitzgen** [comment]
Fixed in #915
