### ISSUE TITLE
Remove the syntex dependency

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#925]
It's deprecated. It has a long build time. We should get off of it.

I think the new hotness is `syn` (or maybe `synom`?) and `quote`?

**Comment by fitzgen** [comment]
I'm working on this.

**Comment by fitzgen** [comment]
Unfortunately, it looks like using the `quote` crate doesn't result in pretty printed Rust code.

**Comment by dtolnay** [comment]
You can pass the output through [`rustfmt::format_input`](https://docs.rs/rustfmt/0.9.0/rustfmt/fn.format_input.html) to make it pretty.

**Comment by fitzgen** [comment]
Unfortunately, `rustfmt` is nightly only now, and `bindgen` can't be nightly only.

I don't think we want to stick to an old `rustfmt` (one that still worked on stable) either. That's no better than sticking with `syntex`.

We recently gained the ability to run the `$PATH`'s `rustfmt` on the generated bindings, and I think we can rely on that functionality here. It's "just" a matter of CI and testing integration.

**Comment by fitzgen** [comment]
This is hItting a bug in rustfmt that is making the formatted rust input invalid: https://github.com/rust-lang-nursery/rustfmt/issues/1914

**Comment by fitzgen** [comment]
Can work around it by using a custom rustfmt.toml and passing it to the rustfmt invocation we use.

**Comment by fitzgen** [comment]
Update: I have a branch without the syntex dependency that can generate bindings for all but one of our test headers (it just hangs in that one test header, and I haven't investigated it yet) and the emitted bindings have changed a little in inconsequential ways but are all passing their layout tests. There is also still some clean up to do and some constify module enums things.

Getting pretty close though.

**Comment by fitzgen** [comment]
I have it passing all tests \o/

There is still some code clean up and minor rebasing to be done before this gets a PR.
