### ISSUE TITLE
Rewrite `has_destructor` as a fixed point analysis

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#927]
Very similar to #765, you could look at the PR that fixed that issue and have a template for fixing this issue.

This will allow us to compute the information once and then cache the results, as well as remove the `detect_has_destructor_cycle` field.

I'm happy to mentor anyone who wants to pick this up.

**Comment by bd339** [comment]
I would like to take a stab at this. I've taken a look at the comments and the PR in #765, as well as the existing code for the has_destructor analysis, so I feel like I have what I need to get started.

**Comment by fitzgen** [comment]
@bd339 great! Let me know if you run into any trouble or have any questions!
