### ISSUE TITLE
Make `BlobTyBuilder` a simple function instead of a builder struct

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#928]
`BlobTyBuilder` is a struct with a `new` method for construction and a `build` method to complete the builder. But it doesn't have any methods to configure the builder or anything like that. So every use is like `BlobTyBuilder::new(..).build()`. This would be better as a simple function `blob(..)`, since we aren't using it as a builder struct at all.

https://github.com/rust-lang-nursery/rust-bindgen/blob/723e93d1267e58cb1aafd04d221a0dff17e212d9/src/codegen/helpers.rs#L63

**Comment by MaloJaffre** [comment]
I'll try to open a PR shortly.
@highfive: assign me
