### ISSUE TITLE
Do the opaque check earlier in `CompInfo::codegen`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#929]
Right now we generate all of a compound type's fields and methods eagerly, and then throw away the result of that computation for opaque types here:

https://github.com/rust-lang-nursery/rust-bindgen/blob/8aa41d195b278d36b9cde9d17c01f5651d9b79b3/src/codegen/mod.rs#L1657-L1675

Instead, we should only codegen the fields and methods if the type isn't opaque in the first place.

**Comment by MaloJaffre** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
@MaloJaffre, were you interested in picking this issue up as well? I saw you left a `@highfive: assign me` comment, but then deleted it. It seems like our highfive bot integrations is half broken right now (probably since the move to rust-lang-nursery)

**Comment by MaloJaffre** [comment]
@fitzgen
Sorry, I've mixed up the two issues.

**Comment by jhod0** [comment]
@fitzgen, I have a fix which is passing tests, but I am not completely sure of its correctness - it doesn't call `struct_layout.saw_vtable()` when `item` is opaque.

I pretty much just added some `if !is_opaque {...}` wrappers around the code paths that add to `fields` and `methods`

**Comment by fitzgen** [comment]
@jhod0 can you make a WIP pull request? That's the easiest way to have discussion about the code. Thanks!

**Comment by jhod0** [comment]
@fitzgen I'll make one later, and ping you when I do

**Comment by jhod0** [comment]
@fitzgen there is now a PR!

**Comment by jhod0** [comment]
@fitzgen  should this be closed?

**Comment by fitzgen** [comment]
Yep, thanks!
