### ISSUE TITLE
Add something like rustc's -Z time-passes

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#933]
This would give a high level overview of how long each of our phases are taking, and help inform us where we should generally be focusing our performance investigations on various test cases.

**Comment by fitzgen** [comment]
Specifically, I'm imagining

* [ ] a new module that provides RAII types for timing start and end of some phase, and printing the timed value in the `Drop` implementation,
* [ ] the ability to turn those RAII timers on/off dynamically via a command line flag and builder option,
* [ ] and then instrumentation of the code base with these RAII timers for all of:
  * [ ] libclang -> IR parsing (`bindgen::parse`)
  * [ ] each of our analyses (eg `bindgen::ir::BindgenContext::compute_cannot_derive_debug`)
  * [ ] `bindgen::ir::BindgenContext::process_replacements`
  * [ ] `bindgen::ir::BindgenContext::compute_whitelisted_and_codegen_items`
  * [ ] IR -> Rust source code (`bindgen::codegen::codegen`)

**Comment by jhod0** [comment]
Would RAII timers work well in rust? I'd think there would be some fighting `unused variable` warnings in the compiler, for code like this:

```
fn some_pass() {
    let t = Timer::new("some_pass");
    // do the work
    // warning - t unused
}
```

**Comment by jhod0** [comment]
@fitzgen I implemented something along these lines, let me know if it's what you had in mind
