### ISSUE TITLE
[Enhancement] Allow to process macro body with ParseCallbacks

### ISSUE THREAD

**Issue by target-san** [rust-lang-nursery/rust-bindgen#937]
ATM if bindgen user needs to parse macros by hand, he's forced to do it manually - know all headers involved, parse them by hand and finally do something with parsing results.

I think it would be beneficial if ParseCallbacks would provide way to not only get notified that certain macro was parsed, but also have its body, at least as a string.
Changes proposed, discussion welcome:
```rust
pub trait ParseCallbacks {
    // Provides callback implementor ways to customize macro parsing
    // @param  name - macro name
    // @param  args - list of macro arguments; None for constant macro;
    //                Some(...) for function-like macro,
    //                with vector containing argument identifiers
    // @param  body - raw macro body as a string slice, allows to parse it by hand
    // @return        None to perform default parsing;
    //                Some(...) to insert specified text into generated bindings module
    fn parsed_macro(&self, name: &str, args: Option<Vec<&str>>, body: &str) -> Option<String>;
    // ... leftover
}
```

**Comment by fitzgen** [comment]
Thanks for the bug report! This is the same issue as https://github.com/rust-lang-nursery/rust-bindgen/issues/666, so let's keep the discussion centralized there.
