### ISSUE TITLE
.opaque_type("std::string")

### ISSUE THREAD

**Issue by ctaggart** [rust-lang-nursery/rust-bindgen#949]
I may misunderstand how opaque types are supposed to work. I though that all references would be treated as a blob of bytes and the references would be removed. The references seem to still be present with `std::string` and other types, but works for `std::map` and a few others. I'm a bit confused.

### Bindgen Invocation
https://github.com/ctaggart/octh/blob/2a32e343bae70632e695f24b1736720ba053cdef/build.rs#L39

### Actual Results
```
error[E0412]: cannot find type `string` in module `root::std`
  --> src/lib.rs:35:43
   |
35 |             pub m_stack_trace: root::std::string,
   |                                           ^^^^^^ not found in `root::std`
```
https://github.com/ctaggart/octh/blob/2a32e343bae70632e695f24b1736720ba053cdef/src/lib.rs#L35

### Expected Results
Something similar to making [std::map opaque](https://github.com/ctaggart/octh/pull/22/commits/5a6b921a6cdd4449ea9245a01af5fed2da6ce844) where it may look like this:
``` rust
        pub m_stack_trace: [u64; 6usize],
```

**Comment by fitzgen** [comment]
Yes, that is certainly a bug.

Can you provide a [reduced, reproducible test case](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases) that exhibits this behavior?

Thanks!

**Comment by ctaggart** [comment]
I ran `time creduce ./predicate.sh __bindgen.ii` last night. It look 110 minutes and output this test case:

``` cpp
namespace std {
inline namespace {
class a typedef string;
class a {};
}
}
namespace octave {
class b {
  std::string m_stack_trace;
};
}
```
Ran with:
``` sh
~/rust-bindgen/target/debug/bindgen \
    --enable-cxx-namespaces \
    --no-layout-tests \
    --opaque-type std::string \
    __bindgen.ii \
    -- -x c++ -std=c++11
```
Outputs:
``` rust
/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod std {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub type string = u8;
        #[repr(C)]
        #[derive(Debug, Copy)]
        pub struct a {
            pub _address: u8,
        }
        impl Clone for a {
            fn clone(&self) -> Self { *self }
        }
    }
    pub mod octave {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy)]
        pub struct b {
            pub m_stack_trace: root::std::string,
        }
        impl Clone for b {
            fn clone(&self) -> Self { *self }
        }
    }
}
```

**Comment by fitzgen** [comment]
Thanks a bunch for the reduced test case! It makes fixing these kinds of bugs much easier!

**Comment by fitzgen** [comment]
Unfortunately, I think the C-Reduce predicate was looking for the slightly wrong thing.

In this reduced test case, `std::string` *is* opaque: it has the correct single-byte layout. In other words, this test case no longer exhibits the bug we were trying to track down.

The predicate script should probably be `grep`ing for 

```
error[E0412]: cannot find type `string` in module `root::std`
```

when attempting to compile the bindings, instead of grepping for `root::std::string` in the bindings themselves.

**Comment by ctaggart** [comment]
@fitzgen That makes sense. A new creduce is running now and I'll report back in the morning (CEST).

**Comment by fitzgen** [comment]
@ctaggart thanks for your dedication!

**Comment by ctaggart** [comment]
It ran all night, 509 minutes, and came up with this:
``` cpp
namespace std {
inline namespace {
class a typedef string;
class a {};
}
}
namespace octave {
class b {
  std::string c;
};
}
```

```
~/rust-bindgen/target/debug/bindgen \
    --output __bindgen.rs \
    --enable-cxx-namespaces \
    --no-recursive-whitelist \
    --whitelist-type octave.* \
    --opaque-type std::string \
    __bindgen.ii \
    -- -v -x c++ -std=c++11

rustc --crate-type=lib __bindgen.rs
```

**Comment by fitzgen** [comment]
Thanks for running C-Reduce again!

> --no-recursive-whitelist \

Is this required to observe the behavior? Because it wasn't in the last set of bindgen flags, and it is expected that using `--no-recursive-whitelist` without providing your own definitions for the referenced types won't compile.

I see that this was set in the builder that was linked to in the original issue; sorry, I should have caught that earlier!

**Comment by fitzgen** [comment]
Yeah, if I remove the `--no-recursive-whitelist` then it compiles just fine.

Sorry! I should have caught that earlier.

I'll make a PR better documenting that `--no-recursive-whitelist` will emit bindings that won't compile.

**Comment by ctaggart** [comment]
Right, but it would compile if `std::string` was added. There doesn't appear to be a way to specify that `std-string` should be included && be opaque. It would be awesome if that was possible. I was hoping that by setting `--opaque-type std::string` that could happen.

Otherwise I am not sure what to do. If I don't set `--no-recursive-whitelist`, I pull in the entire kitchen sink. Open to suggestions.

**Comment by fitzgen** [comment]
> Otherwise I am not sure what to do. If I don't set --no-recursive-whitelist, I pull in the entire kitchen sink. Open to suggestions.

I think your best option is to `--opaque-type 'std::.*'` and live with the extra types.

**Comment by ctaggart** [comment]
I'll give that a shot. Thanks.
