### ISSUE TITLE
Bindgen generates getters and setters which access memory beyond "self"

### ISSUE THREAD

**Issue by glyn** [rust-lang-nursery/rust-bindgen#954]
A getter can read bytes beyond "self" and a setter can read and write bytes beyond "self".

For instance, in [this example](https://github.com/rust-lang-nursery/rust-bindgen/blob/cb1059786df114cae72b8baea038dc5ea638269d/tests/expectations/tests/bitfield-32bit-overflow.rs#L28), a getter copies 8 bytes from a 5 (I [checked](https://play.rust-lang.org/?gist=ac531c5f0c58b49ad1ece748d2aba234&version=stable)) byte struct. The setter in this example copies 8 bytes from a 5 byte struct and writes back an updated 8 bytes over the top of the struct.

**Comment by fitzgen** [comment]
Thanks for the bug report!
