### ISSUE TITLE
TemplateParameters' methods should just return a Vec, not an Option<Vec>

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#960]
I thought that the `Option` would be useful, but in practice we do pretty much ignore that it is an option and do things like `params.unwrap_or(vec![])`. And then in other places when the result is `Some` we assume that the contained `Vec` is not empty, when that isn't always the case.

It will be much simpler to just return a `Vec` that is either empty or not.

And also `usize` instead of `Option<usize>` for `num_self_template_params`.

The trait's comment will need to be updated as well.

https://github.com/rust-lang-nursery/rust-bindgen/blob/cd41e5cfe26555af574e81b6aa3bed2b84a18000/src/ir/template.rs#L102

**Comment by hgallagher1993** [comment]
Ya I'll take this @highfive: assign me

**Comment by fitzgen** [comment]
@hgallagher1993 let me know if you have any questions!

**Comment by fitzgen** [comment]
@hgallagher1993 making any progress here? Anything I can help with?

**Comment by hgallagher1993** [comment]
Yes I have been making progress, There's only a couple compilation errors and then the comments so I should have a pull request in the next day or 2

**Comment by hgallagher1993** [comment]
@fitzgen Just as an update this is finished but I'm going to a wedding for the weekend so I'll just make the pull request when I'm back at my laptop on Monday or Tuesday

**Comment by fitzgen** [comment]
Enjoy the wedding :)

**Comment by Megamiun** [comment]
Hello, this issue is still open, no?

I can try to solve this, if yes.

**Comment by emilio** [comment]
There's #1245, which should be pretty close to be landable.

**Comment by Megamiun** [comment]
Oh, I confounded this PR with the other. Hope it goes alright with this PR!
