### ISSUE TITLE
Allow specifying certain types we shouldn't derive/impl Copy for

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#962]
Add `--no-copy <regex>` and `Builder::no_copy(String)` to supply regexes for matching against types that we should not derive or implement `Copy` for.

Adding this feature involves:

* [ ] Adding a new `RegexSet` member to `bindgen::Builder` (similar to the `whitelisted_types` set).

* [ ] A `Builder` method to add strings to that `RegexSet`.

* [ ] Plumbing in `src/options.rs` to convert `--no-copy <regex>` CLI flags into invocations of the builder method.

* [ ] Making the `MonotoneFramework::constrain` function in `src/ir/analysis/derive_copy.rs` check if the given item is explicitly marked not to be `Copy`, and if so, inserting it into the `self.cannot_derive_copy` set via `return self.insert(id)`.

* [ ] Tests!

    * [ ] When the no-copy type is transitively referenced by a whitelisted item

    * [ ] When the no-copy type is explicitly whitelisted

    * [ ] When the no-copy type is marked opaque

**Comment by hallfox** [comment]
Hi! I'd like to take a crack at this.

**Comment by fitzgen** [comment]
Great! Let me know if you have any questions :)
