### ISSUE TITLE
Allow specifying certain types we shouldn't derive/impl Hash for

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#964]
Add `--no-hash <regex>` and `Builder::no_hash(String)` to supply regexes for matching against types that we should not derive or implement `Hash` for.

Adding this feature involves:

* [ ] Adding a new `RegexSet` member to `bindgen::Builder` (similar to the `whitelisted_types` set).

* [ ] A `Builder` method to add strings to that `RegexSet`.

* [ ] Plumbing in `src/options.rs` to convert `--no-hash <regex>` CLI flags into invocations of the builder method.

* [ ] Making the `MonotoneFramework::constrain` function in `src/ir/analysis/derive_hash.rs` check if the given item is explicitly marked not to be `Hash`, and if so, inserting it into the `self.cannot_derive_hash` set via `return self.insert(id)`.

* [ ] Tests!

    * [ ] When the no-hash type is transitively referenced by a whitelisted item

    * [ ] When the no-hash type is explicitly whitelisted

    * [ ] When the no-hash type is marked opaque

**Comment by treiff** [comment]
I'll give this a shot. @highfive: assign me

**Comment by fitzgen** [comment]
@treiff making any progress here? Anything that I can help with?

**Comment by treiff** [comment]
Hey @fitzgen, sorry for the delay.  I had made a little progress, however I've got a bunch going on with work and don't think I'm actually going to have the time to give this the attention it needs. Probably best you un-assign me.

Thanks for the follow up reminder.

**Comment by fitzgen** [comment]
No problem!

**Comment by seemyvest** [comment]
@highfive: assign me

**Comment by emilio** [comment]
Fixed by  #1105
