### ISSUE TITLE
Allow specifying certain types we shouldn't derive/impl PartialEq for

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#965]
Add `--no-partialeq <regex>` and `Builder::no_partialeq(String)` to supply regexes for matching against types that we should not derive or implement `PartialEq` for.

Adding this feature involves:

* [ ] Adding a new `RegexSet` member to `bindgen::Builder` (similar to the `whitelisted_types` set).

* [ ] A `Builder` method to add strings to that `RegexSet`.

* [ ] Plumbing in `src/options.rs` to convert `--no-partialeq <regex>` CLI flags into invocations of the builder method.

* [ ] Making the `MonotoneFramework::constrain` function in `src/ir/analysis/derive_partialeq.rs` check if the given item is explicitly marked not to be `Partialeq`, and if so, inserting it into the `self.cannot_derive_partialeq` set via `return self.insert(id)`.

* [ ] Tests!

    * [ ] When the no-partialeq type is transitively referenced by a whitelisted item

    * [ ] When the no-partialeq type is explicitly whitelisted

    * [ ] When the no-partialeq type is marked opaque

**Comment by alexeyzab** [comment]
I'd like to try adding this one.

@highfive: assign me
