### ISSUE TITLE
Doesn't derive Debug for all structs

### ISSUE THREAD

**Issue by Ploppz** [rust-lang-nursery/rust-bindgen#974]
With `.derive_debug(true)` on the Builder, `Debug` doesn't get derived for all types. Complete example: https://github.com/Ploppz/mcp2210-bindings

... in which this struct doesn't get Debug implemented:
```
pub struct SPIDataTransferStatusDef {
    pub NumberOfBytesReceived: c_uint,
    pub SPIEngineStatus: c_uint,
    pub DataReceived: [c_uchar; 60],
    pub ErrorCode: c_int,
}
```

**Comment by fitzgen** [comment]
This is expected because the `DataReceived` array is has more elements than the maximum number of elements for which Rust implements `Debug` for arrays (32).

You can use `Builder::impl_debug` and/or `--impl-debug` to have `bindgen` generate an `impl Debug for ...` block.
