### ISSUE TITLE
Add a `Builder::blacklist_type` method; deprecate `Builder::hide_type`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#984]
Currrently, the `--blacklist-type` flag's corresponding `Builder` method is `Builder::hide_type`.

The naming difference is unnecessary, inconsistent, makes it harder for users to switch from CLI to builder or vice versa, and adds one more thing to remember/know about the code base when developers are reading about hidden or blacklisted things.

We should:

* [ ] Add `Builder::blacklist_type`, that does the same thing as `hide_type`
* [ ] Mark `Builder::hide_type` as `#[deprecated = "Use blacklist_type instead"]`
* [ ] Make `hide_type` delegate to `blacklist_type`
* [ ] Rename the `BindgenOptions::hidden_types` member to `BindgenOptions::blacklisted_types`
* [ ] Rename `ir::context::BindgenContext::hidden_by_name` to `blacklisted_by_name`
* [ ] Rename `ir::item::Item::is_hidden` to `is_blacklisted`

**Comment by alexeyzab** [comment]
Hi! I'd like to try implementing this.

@highfive: assign me

**Comment by tamird** [comment]
fixed in #991

**Comment by fitzgen** [comment]
Thanks for the reminder, @tamird !

@alexeyzab, fwiw, if you add "Fixes #12345" in the git commit message, github will automatically close the issue once the relevant PR is merged.
