### ISSUE TITLE
Add `Builder::whitelist_function`; deprecate `Builder::whitelisted_function`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#985]
The CLI flag is `--whitelist-function`, so we should be consistent and remove the "ed" from the builder method.

* [ ] Rename `Builder::whitelisted_function` to `Builder::whitelist_function`
* [ ] Add `Builder::whitelisted_function` that delegates to `whitelist_function`
* [ ] Mark `whitelisted_function` as `#[deprecated = "use whitelist_function instead"`]

**Comment by treiff** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
@treiff if you run into any questions, don't hesitate to ping me :)
