### ISSUE TITLE
Add `Builder::whitelist_var`; deprecate `Builder::whitelisted_var`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#986]
The CLI flag is `--whitelist-var`, so we should be consistent and remove the "ed" from the builder method.

* [ ] Rename `Builder::whitelisted_var` to `Builder::whitelist_var`
* [ ] Add `Builder::whitelisted_var` that delegates to `whitelist_var`
* [ ] Mark `whitelisted_var` as `#[deprecated = "use whitelist_var instead"]`

**Comment by aeleos** [comment]
@highfive: assign me

**Comment by fitzgen** [comment]
@aeleos don't hesitate to ping me if you have any questions :)

**Comment by aeleos** [comment]
@fitzgen I do have one question, is there any recommended place to put the old deprecated function? I am thinking right next to it is probably best, but at the bottom could also work.

**Comment by aeleos** [comment]
@fitzgen I lied I do have another question, I ended up with this code

    /// Whitelist the given variable so that it (and all types that it
    /// transitively refers to) appears in the generated bindings. Regular
    /// expressions are supported.
    pub fn whitelist_var<T: AsRef<str>>(mut self, arg: T) -> Builder {
        self.options.whitelisted_vars.insert(arg);
        self
    }

    /// Whitelist the given variable.
    ///
    /// Deprecated: use whitelist_var instead.
    #[deprecated = "use whitelist_var instead"]
    pub fn whitelisted_var<T: AsRef<str>>(self, arg: T) -> Builder {
        self.whitelist_var(arg)
    }

The compiler said that I didn't need mut self on the deprecated function, and just self was fine. It compiles but it strikes me as odd, does it make sense to you or is there a problem I am not seeing

**Comment by fitzgen** [comment]
> I am thinking right next to it is probably best, but at the bottom could also work.

Right next to it is fine.

> The compiler said that I didn't need mut self on the deprecated function, and just self was fine. It compiles but it strikes me as odd, does it make sense to you or is there a problem I am not seeing

There is no problem you're not seeing.

To call a method that takes `self` by value, you don't need `mut`, but to modify any of `self`'s fields locally you need `mut`. Its a bit funky. This sparked a huge discussion right before Rust 1.0, but ultimately we stayed with what we currently have: https://www.reddit.com/r/rust/comments/25i544/babysteps_focusing_on_ownership_or_removing_let/

**Comment by aeleos** [comment]
@fitzgen ah thanks for the info. I created a PR, hopefully I did it correctly.
