### ISSUE TITLE
Add `Builder::whitelist_type`; deprecate `Builder::whitelisted_type`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#987]
The CLI flag is `--whitelist-type`, so we should be consistent and remove the "ed" from the builder method.

* [ ] Rename `Builder::whitelisted_type` to `Builder::whitelist_type`
* [ ] Add `Builder::whitelisted_type` that delegates to `whitelist_type`
* [ ] Mark `whitelisted_type` as `#[deprecated = "use whitelist_type instead"]`

**Comment by treiff** [comment]
Going to grab this one, then maybe start looking at some of the slightly more difficult ones. 

@highfive: assign me
