### ISSUE TITLE
variadic function must have C or cdecl calling convention

### ISSUE THREAD

**Issue by helloqirun** [rust-lang-nursery/rust-bindgen#997]
I am using this script https://gist.github.com/fitzgen/187381e358f60efa8194d0b276b4d11a.

The hashtag for my bindgen version is 4dd4ac7 .

$ ./b.sh bindgen abc.h
```
clang-4.0: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
error[E0045]: variadic function must have C or cdecl calling convention
 --> /tmp/bindings-CLx7tG.rs:5:2
  |
5 |  pub fn a ( arg1 : :: std :: os :: raw :: c_char , ... ) -> :: std :: os :: raw :: c_char ;
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variadics require C or cdecl calling convention

error: aborting due to previous error

Interesting: bindgen emitted Rust code that won't compile!
```

$ cat abc.h
```
char __attribute__((ms_abi)) a(char, ...);
```

**Comment by fitzgen** [comment]
Ooo this is a nice bug catch :)

What I think is going on is that `ms_abi` is an unknown ABI for us, and so we don't specify the function having any particular ABI when we emit bindings to it, and then this blows up in `rustc`.

In the long term, we should properly support this ABI, which requires getting `rustc` to properly support it first.

In the immediate term, I think what we should do in this case is simply not emit the bindings (and `warn!` that we aren't doing it).

**Comment by oldmanmike** [comment]
@fitzgen Would it be cool if I tackle this bug?

**Comment by fitzgen** [comment]
@oldmanmike sure thing! Let me know if you need any pointers or anything :)

**Comment by fitzgen** [comment]
@oldmanmike still hacking on this? Any questions I can answer?

**Comment by fitzgen** [comment]
Unassigning due to lack of activity.

**Comment by jeanphilippeD** [comment]
Hello, I have started looking at this bug and should have a pull request for it soon that follow the advice of warning and not generating the binding.
